import { startAttempt, remaining, touch, choose, navigate, finish, analyze, readHistory, writeHistory, attemptQuestions } from './model.mjs?v=auto-reasoning-1';
import {generatedForm} from './generated.mjs';
import { visualMarkup } from './visuals.mjs?v=auto-reasoning-1';
import {setGeometryIcon} from '../math-teaching/geometry-icons.mjs';
import './readings.mjs?v=auto-reasoning-1';
import { annotate } from '../math-foundations/zhuyin.mjs';
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(action,symbol,label,extra='')=>`<button class="icon" data-action="${action}" aria-label="${label}" title="${label}" ${extra}>${symbol}</button>`;
const bankPromise=fetch(new URL('./bank.json?v=auto-reasoning-1',import.meta.url)).then(r=>{if(!r.ok)throw new Error('題庫尚未載入');return r.json();}).then(bank=>({...bank,forms:[...bank.forms,generatedForm],categories:{...bank.categories,area:{title:'面積與周長推理',lesson:'math-geometry.html?mode=area',unit:'3-09、3-10',practice:'逐格數面積、沿外框數周長，內部共用邊不算周長。'}}}));
class MockExam extends HTMLElement {
 static observedAttributes=['learner-id'];
 constructor(){super();this.attachShadow({mode:'open'});this.view='home';this.zhuyin=false;this.sound=false;this.filter='all';this.confirming=false;this.storageWarning=false;this.connected=false;this.state={active:null,history:[]};this.onClick=e=>this.click(e);this.onKey=e=>{if(!this.confirming)return;const buttons=[...this.shadowRoot.querySelectorAll('.confirm button')];if(e.key==='Escape'){e.preventDefault();this.confirming=false;this.render();this.shadowRoot.querySelector('[data-action=submit]')?.focus();}if(e.key==='Tab'){const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&this.shadowRoot.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&this.shadowRoot.activeElement===last){e.preventDefault();first.focus();}}};}
 connectedCallback(){this.connected=true;this.shadowRoot.addEventListener('click',this.onClick);this.shadowRoot.addEventListener('keydown',this.onKey);bankPromise.then(bank=>{if(!this.connected)return;this.bank=bank;this.load();this.timer=setInterval(()=>this.tick(),500);}).catch(()=>{this.shadowRoot.innerHTML='<p>題庫載入失敗，請重新整理。</p>';});}
 disconnectedCallback(){this.connected=false;clearInterval(this.timer);this.shadowRoot.removeEventListener('click',this.onClick);this.shadowRoot.removeEventListener('keydown',this.onKey);this.releaseDiagram();if(this.bank&&this.state.active){touch(this.state.active);this.save();}if(this.sound)window.speechSynthesis?.cancel();}
 attributeChangedCallback(name,oldValue,newValue){if(oldValue!==newValue&&this.bank&&this.connected){if(this.sound)window.speechSynthesis?.cancel();this.zhuyin=false;this.sound=false;this.load();}}
 get learner(){return this.getAttribute('learner-id')||'';}
 load(){this.state=readHistory(localStorage,this.learner,this.bank);this.view='home';this.record=null;this.confirming=false;this.tick();this.render();}
 save(){this.storageWarning=!writeHistory(localStorage,this.learner,this.state);}
 form(){return this.bank.forms.find(f=>f.id===(this.record||this.state.active)?.formId);}
 questions(){return attemptQuestions(this.record||this.state.active,this.bank);}
 tick(){const active=this.state.active;if(!active)return;if(remaining(active)===0){this.submit();return;}const node=this.shadowRoot.querySelector('[data-timer]');if(node)node.textContent=this.clock(remaining(active));}
 clock(seconds){return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
 submit(){const active=this.state.active;if(!active)return;finish(active);this.state.history=[active,...this.state.history.filter(a=>a.id!==active.id)].slice(0,30);this.record=active;this.state.active=null;this.view='result';this.filter='all';this.confirming=false;this.save();this.render();}
 async click(event){const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;
  if(action==='camera'){this.diagram?.angle(button.dataset.angle);return;}
  if(action==='layers'){if(this.diagram){this.diagram.toggleLayers();this.updateLayerIcon();}return;}
  if(action==='zhuyin'){this.zhuyin=!this.zhuyin;this.render();return;}
  if(action==='sound'){this.sound=!this.sound;if(!this.sound)window.speechSynthesis?.cancel();else this.speak();this.render();return;}
  if(this.state.active&&remaining(this.state.active)===0){this.submit();return;}
  if(action==='start'){if(this.state.active)return;const form=this.bank.forms.find(f=>f.id===button.dataset.id);if(!form||!this.learner)return;this.state.active=startAttempt(form,Date.now(),crypto.randomUUID(),crypto.getRandomValues(new Uint32Array(1))[0]);this.view='exam';this.save();}
  if(action==='resume'){this.view='exam';}
  if(action==='pick'&&this.state.active){choose(this.state.active,Number(button.dataset.option));this.save();}
  if(action==='question'&&this.state.active){navigate(this.state.active,Number(button.dataset.index));this.save();}
  if(action==='prev'&&this.state.active){navigate(this.state.active,this.state.active.index-1);this.save();}
  if(action==='next'&&this.state.active){navigate(this.state.active,this.state.active.index+1);this.save();}
  if(action==='flag'&&this.state.active){this.state.active.flags[this.state.active.index]=!this.state.active.flags[this.state.active.index];this.save();}
  if(action==='submit'){this.confirming=true;}
  if(action==='cancel-submit'){this.confirming=false;}
  if(action==='confirm-submit'){this.submit();return;}
  if(action==='home'){if(this.state.active){touch(this.state.active);this.save();}this.view='home';this.record=null;this.confirming=false;}
  if(action==='history'){this.record=this.state.history.find(a=>a.id===button.dataset.id);if(this.record){this.view='result';this.filter='all';}}
  if(action==='filter'){this.filter=button.dataset.filter;}
  this.render();if(this.sound&&['start','resume','question','prev','next'].includes(action))this.speak();
 }
 speak(){if(this.view!=='exam'||!this.state.active)return;const question=this.questions()[this.state.active.index];const value=new SpeechSynthesisUtterance(question.stem+'。'+question.options.map((s,i)=>`選項${i+1}，${s}`).join('。'));value.lang='zh-TW';value.rate=.85;window.speechSynthesis?.cancel();window.speechSynthesis?.speak(value);}
 header(){return `<div class="bar"><div class="grow"><span class="kicker">LEARNING PLANET · MOCK EXAM</span><h2>模擬考</h2></div>${icon('zhuyin','ㄅ','注音切換',`aria-pressed="${this.zhuyin}"`)}${icon('sound',this.sound?'🔊':'🔇','朗讀開關',`aria-pressed="${this.sound}"`)}</div>`;}
 home(){return `<section class="hero">${this.header()}<p class="home-note">小二升小三 · 數量、空間、條件、讀題</p><p class="muted">原創推理卷每次自動出題；歷史卷為固定的數學學力診斷。成績只用來安排補練，不換算智商或錄取機率。</p><a class="report-link" href="gifted-learning-path.html" target="_blank" rel="noopener">家長學習路徑 ↗</a></section>
 ${!this.learner?'<p class="notice">請先登入學生帳號，再開始模擬考。</p>':''}
 ${this.state.active?`<section class="panel"><h3>有一份未交卷</h3><p>${escape(this.form().title)} · 剩 <span data-timer>${this.clock(remaining(this.state.active))}</span></p><p class="muted">離開頁面後仍繼續計時。</p><button class="primary" data-action="resume">▶ 繼續</button></section>`:''}
 <div class="cards">${this.bank.forms.map(form=>`<section class="panel form-card"><span class="tag">${form.source==='history115'?'歷史學力':form.source==='generated'?'每次換題':'原創推理'}</span><h3>${form.title}</h3><p>${form.questionIds.length} 題 · ${form.minutes} 分鐘</p><p class="muted">${form.subtitle}</p><button class="primary" data-action="start" data-id="${form.id}" ${!this.learner||this.state.active?'disabled':''} aria-label="開始${form.title}">▶</button></section>`).join('')}</div>
 <section class="panel"><h3>作答紀錄</h3><p class="muted">保留此裝置此學生最近 30 次；每週考卷與獎勵獨立計算。</p>${this.state.history.length?this.state.history.map(a=>{const r=analyze(a,this.bank),f=this.bank.forms.find(x=>x.id===a.formId);return `<div class="history-item"><div>${f.title}<br><span class="muted">${new Date(a.finishedAt).toLocaleString('zh-TW')} · ${r.correct}/${r.total}</span></div>${icon('history','↻','查看考後分析',`data-id="${escape(a.id)}"`)}</div>`;}).join(''):'<p class="muted">還沒有交卷紀錄。</p>'}</section>`;}
 exam(){const a=this.state.active;if(!a)return '';const questions=this.questions(),q=questions[a.index],answered=a.answers.filter(x=>x!==null).length;
 return `<section class="panel"><div class="bar">${icon('home','←','回到模擬考選單')}<span class="grow">${this.form().title}</span>${icon('zhuyin','ㄅ','注音切換',`aria-pressed="${this.zhuyin}"`)}${icon('sound',this.sound?'🔊':'🔇','朗讀開關',`aria-pressed="${this.sound}"`)}<strong class="timer" data-timer aria-label="剩餘時間">${this.clock(remaining(a))}</strong></div><div class="progress"><i style="width:${answered/questions.length*100}%"></i></div><div class="bar"><span class="grow">${a.index+1} / ${questions.length}</span><span class="muted">已答 ${answered}</span>${icon('flag','⚑','標記待檢查',`aria-pressed="${a.flags[a.index]}"`)}</div></section>
 <div class="exam-layout"><section class="scene"><h2>${escape(q.stem)}</h2>${this.questionDiagram(q)}<div class="options" role="group" aria-label="答案選項">${q.options.map((option,i)=>`<button class="option" data-action="pick" data-option="${i}" aria-pressed="${a.answers[a.index]===i}"><b>${i+1}</b><span>${escape(option)}</span></button>`).join('')}</div><div class="bar exam-footer">${icon('prev','←','上一題',a.index===0?'disabled':'')}${icon('next','→','下一題',a.index===questions.length-1?'disabled':'')}</div></section><aside class="panel"><div class="navgrid" aria-label="題號導覽">${questions.map((_,i)=>`<button class="${a.answers[i]===null?'':'answered'} ${a.flags[i]?'flagged':''} ${a.index===i?'current':''}" data-action="question" data-index="${i}" aria-label="第 ${i+1} 題${a.answers[i]===null?'未作答':'已作答'}${a.flags[i]?'，待檢查':''}" ${i===a.index?'aria-current="step"':''}>${i+1}</button>`).join('')}</div><p class="muted">⚑ 待檢查</p><button class="primary" data-action="submit" aria-haspopup="dialog">✓ 交卷</button></aside></div>
 ${this.confirming?`<div class="confirm" role="dialog" aria-modal="true" aria-label="確認交卷"><section class="panel"><h3>確定交卷？</h3><p>尚有 ${questions.length-answered} 題未作答，${a.flags.filter(Boolean).length} 題待檢查。</p><div class="bar"><button data-action="cancel-submit">← 回去檢查</button><button class="primary" data-action="confirm-submit">✓ 交卷</button></div></section></div>`:''}`;
 }
 result(){const r=analyze(this.record,this.bank);const filters=[['all','全部'],['correct','✓'],['wrong','×'],['skipped','—']];const weak=r.categories.filter(g=>g.correct<g.total);return `<section class="hero"><div class="bar">${icon('home','←','回到模擬考選單')}<h2 class="grow">考後分析</h2>${icon('zhuyin','ㄅ','注音切換',`aria-pressed="${this.zhuyin}"`)}</div><p>${this.form().title} · 用時 ${this.clock(r.seconds)}</p><div class="stats"><div class="stat"><strong>${r.score}</strong>分</div><div class="stat correct"><strong>${r.correct}</strong>✓ 答對</div><div class="stat wrong"><strong>${r.wrong}</strong>× 答錯</div><div class="stat skipped"><strong>${r.skipped}</strong>— 未答</div></div></section>
 <section class="panel"><h3>接下來練什麼</h3>${r.categories.map(g=>`<div class="catrow"><span>${this.bank.categories[g.category].title}</span><span>${g.correct}/${g.total} · ${g.accuracy}%</span><div class="progress"><i style="width:${g.accuracy}%"></i></div></div>`).join('')}<p class="muted">答對率以該類全部題目計算，未作答也列入分母；小題量只作補練線索。</p>${weak.length?weak.slice(0,3).map(g=>{const c=this.bank.categories[g.category];return `<p><a class="lesson" href="${c.lesson}" target="_blank" rel="noopener">${c.title} ↗</a> · ${c.practice}</p>`;}).join(''):'<p>這份全部答對了。隔幾天換另一份題卷，看看能不能解釋自己的方法。</p>'}</section>
 <div class="bar tabs" role="group" aria-label="逐題分析篩選">${filters.map(([id,label])=>`<button data-action="filter" data-filter="${id}" aria-pressed="${this.filter===id}" aria-label="${{all:'全部題目',correct:'答對題目',wrong:'答錯題目',skipped:'未作答題目'}[id]}">${label}</button>`).join('')}</div>
 ${r.rows.filter(row=>this.filter==='all'||row.status===this.filter).map(row=>{const q=row.question,c=this.bank.categories[q.category];return `<details class="review" ${this.filter!=='all'?'open':''}><summary><strong class="${row.status}">${{correct:'✓',wrong:'×',skipped:'—'}[row.status]} ${row.number}</strong><span class="grow">${c.title}</span><span class="muted">${row.seconds} 秒 ▾</span></summary><p class="stem">${escape(q.stem)}</p>${visualMarkup(q.visual)}<ol>${q.options.map((o,i)=>`<li class="${i===q.correct?'answer-correct':''} ${i===row.picked?'answer-picked':''}">${escape(o)} ${i===q.correct?'✓':''} ${i===row.picked?'← 我的答案':''}</li>`).join('')}</ol><p>${row.picked===null?'未作答':`我的答案：${row.picked+1}`} · 正確答案：${q.correct+1}</p><div class="explain"><p>${escape(q.explain)}</p><p>${row.status==='correct'?'再檢查觀念':'補練提示'}：${escape(q.check)}</p></div><p class="muted">${q.source==='history115'?`來源：使用者提供 115 年三年級學力檢測第 ${row.number} 題，文字與圖重排，答案核對原附答案表。`:'來源：Learning Planet 原創推理練習。'}</p><a class="lesson" href="${c.lesson}" target="_blank" rel="noopener">觀念教學 ↗</a></details>`;}).join('')||'<p class="panel">這個分類沒有題目。</p>'}`;}
 releaseDiagram(){if(this.diagram){this.diagram.destroy();this.diagram=null;}this.diagramGeneration=(this.diagramGeneration||0)+1;}
 questionDiagram(q){if(q.visual?.kind!=='cubes3d')return visualMarkup(q.visual);return `<div class="three-diagram" data-three>${visualMarkup(q.visual)}</div><div class="bar camera-tools">${[['home','◇','三面視角'],['front','▣','正面'],['side','◧','側面'],['top','▤','俯視']].map(([angle,symbol,label])=>icon('camera',symbol,label,`data-angle="${angle}"`)).join('')}${icon('layers','','拆層觀察')}</div>`;}
 updateLayerIcon(){const button=this.shadowRoot.querySelector('[data-action=layers]');if(button){const split=this.diagram?.split;setGeometryIcon(button,split?'all':'split',split?'完整積木':'拆層觀察');button.setAttribute('aria-pressed',Boolean(split));}}
 mountDiagram(){
  const host=this.shadowRoot.querySelector('[data-three]');if(!host){this.releaseDiagram();return;}
  const q=this.questions()[this.state.active.index],key=this.state.active.id+q.id;
  if(this.diagram?.key===key){host.replaceWith(this.diagram.host);return;}
  this.releaseDiagram();const generation=this.diagramGeneration;
  const current=()=>this.connected&&generation===this.diagramGeneration&&host.isConnected;
  const fail=()=>{if(!current())return;host.querySelector('canvas')?.remove();const note=document.createElement('p');note.className='muted';note.textContent='立體顯示無法啟動，請換支援立體圖形的瀏覽器作答。';host.after(note);this.shadowRoot.querySelectorAll('[data-action=camera],[data-action=layers]').forEach(b=>b.disabled=true);};
  import('./three-diagram.mjs').then(({attachThreeDiagram})=>{if(!current())return;const fallback=host.firstElementChild;try{this.diagram=attachThreeDiagram(host,q.visual);this.diagram.key=key;fallback?.remove();this.updateLayerIcon();}catch{fail();}}).catch(fail);
 }

 render(){if(!this.bank)return;const focused=this.shadowRoot.activeElement?.dataset;const action=focused?.action,option=focused?.option,index=focused?.index;this.shadowRoot.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css',import.meta.url).href}">${this.storageWarning?'<p class="notice" role="status">此瀏覽器無法保存紀錄；離開前請完成作答並保存分析。</p>':''}${this.view==='exam'?this.exam():this.view==='result'&&this.record?this.result():this.home()}`;this.shadowRoot.querySelectorAll('[data-action=camera]').forEach(button=>setGeometryIcon(button,button.dataset.angle,button.getAttribute('aria-label')));this.mountDiagram();this.updateLayerIcon();if(this.zhuyin)annotate(this.shadowRoot,{includeControls:true});if(this.confirming)this.shadowRoot.querySelector('.confirm button')?.focus();else if(action){const selector=`[data-action="${action}"]${option!==undefined?`[data-option="${option}"]`:''}${index!==undefined?`[data-index="${index}"]`:''}`;this.shadowRoot.querySelector(selector)?.focus();}}
}
if(!customElements.get('lp-mock-exam'))customElements.define('lp-mock-exam',MockExam);
