import {mountShelf} from './shelf';
import './style.css';
type Page={id:string;title:string;text:string;image:string};
type Book={id:string;title:string;cover:string;video:string;pages:Page[]};
const root=document.querySelector<HTMLElement>('#story-app')!;
root.style.backgroundImage="radial-gradient(ellipse at 50% 42%,#34436988,transparent 65%),url('images/experiments/shared-classroom/v1/classroom.png')";
let books:Book[]=[],selected=0,page=0,mode:'shelf'|'read'|'video'='shelf',cleanup=()=>{},speaking=false,slow=false,epoch=0;
let part=0,paused=false;
let syncSentence=()=>{};
let playbackButton:HTMLButtonElement|undefined;
function syncPlayback(){if(!playbackButton)return;const active=speaking&&!paused;playbackButton.textContent=active?'Ⅱ':'▶';const label=active?'暫停朗讀':paused?'繼續朗讀':'播放朗讀';playbackButton.setAttribute('aria-label',label);playbackButton.title=label;playbackButton.setAttribute('aria-pressed',String(active));}
function togglePlayback(){if(speaking&&!paused){speechSynthesis.pause();paused=true;status.textContent='已暫停';syncPlayback();}else if(paused){speechSynthesis.resume();paused=false;status.textContent='';syncPlayback();}else speak();}
function lineIcon(b:HTMLButtonElement,paths:string){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('width','25');svg.setAttribute('height','25');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths);svg.append(path);b.replaceChildren(svg);return b;}
const chunks=(text:string)=>text.match(/[^。！？\n]+[。！？]?/g)||[text];

function stopVoice(){epoch++;window.speechSynthesis?.cancel();speaking=false;paused=false;syncPlayback();}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text=''){const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;}
function button(icon:string,label:string,action:()=>void){const b=el('button','sp-icon',icon);b.type='button';b.setAttribute('aria-label',label);b.title=label;b.onclick=action;return b;}
function saved(){try{return Math.min(books[selected].pages.length-1,Math.max(0,Number(localStorage.getItem('story-page-'+books[selected].id))||0));}catch{return 0;}}
function remember(){try{localStorage.setItem('story-page-'+books[selected].id,String(page));}catch{/* Reading works without storage. */}}
function speak(){stopVoice();if(!window.speechSynthesis){status.textContent='此裝置沒有語音，可直接閱讀字幕。';return;}const text=books[selected].pages[page].text||books[selected].title;const sentences=chunks(text);const token=epoch;speaking=true;syncPlayback();const next=(i:number)=>{if(token!==epoch||mode!=='read')return;if(i>=sentences.length){speaking=false;syncPlayback();status.textContent='換你翻頁';return;}part=i;syncSentence();subtitle.textContent=sentences[i];subtitle.hidden=false;const u=new SpeechSynthesisUtterance(sentences[i]);u.lang='zh-TW';u.rate=slow?.7:.9;u.onend=()=>next(i+1);u.onerror=()=>{if(token!==epoch)return;speaking=false;syncPlayback();status.textContent='語音暫時不可用，仍可自由翻頁。';};speechSynthesis.speak(u);};next(part);}
let status:HTMLElement,subtitle:HTMLButtonElement;
function render(){part=0;cleanup();cleanup=()=>{};stopVoice();root.replaceChildren();const header=el('header','sp-header');header.append(button('←',mode==='shelf'?'回首頁':'回書架',()=>{if(mode==='shelf')location.href='index.html';else{mode='shelf';render();}}),el('h1','',mode==='shelf'?'故事星球':books[selected].title));const stage=el('section','sp-stage');const footer=el('footer','sp-footer');status=el('span','sp-status');status.setAttribute('role','status');root.append(header,stage,footer);
 if(mode==='shelf'){root.style.backgroundImage="url('images/story/library-hall-v1.png')";stage.classList.add('sp-library-stage');const shelfPage=Math.floor(selected/6);const first=shelfPage*6;const shown=books.slice(first,first+6);const prev=button('‹','上一排書',()=>{selected=Math.max(0,first-6);render();});prev.disabled=first===0;const next=button('›','下一排書',()=>{selected=first+6;render();});next.disabled=first+6>=books.length;footer.append(prev,el('span','sp-title',`魔法圖書館 · ${books.length} 本故事`),next);stage.append(el('div','sp-caption','點書脊，抽出故事'));cleanup=mountShelf(stage,shown,index=>{selected=first+index;page=saved();mode='read';render();});return;}
 root.style.backgroundImage="radial-gradient(ellipse at 50% 42%,#34436988,transparent 65%),url('images/experiments/shared-classroom/v1/classroom.png')";
 header.append(lineIcon(button('','觀看故事影片',()=>{mode=mode==='video'?'read':'video';render();}),'M4 14v-3a8 8 0 0 1 16 0v3 M4 13H3v7h4v-7H4 M20 13h1v7h-4v-7h3'));
 if(mode==='video'){const frame=document.createElement('iframe');frame.src=`https://www.youtube-nocookie.com/embed/${books[selected].video}?rel=0`;frame.title=books[selected].title+'影片';frame.allow='fullscreen; picture-in-picture';frame.allowFullscreen=true;stage.append(frame);footer.append(button('▤','進入故事閱讀',()=>{mode='read';render();}),el('span','sp-title','看完了，翻開故事書'));return;}
 stage.classList.add('is-reading');const p=books[selected].pages[page];const img=el('img','sp-page');img.src=p.image;img.alt=p.title;img.onerror=()=>{status.textContent='這頁圖片載入失敗，可翻頁或稍後再試。';};subtitle=el('button','sp-subtitle',chunks(p.text)[part]);subtitle.setAttribute('aria-label','重聽這一段');subtitle.hidden=page<2;subtitle.onclick=speak;stage.append(img,subtitle);playbackButton=button('▶','播放朗讀',togglePlayback);syncPlayback();header.append(playbackButton,button('字','顯示或隱藏文字',()=>{subtitle.textContent=chunks(p.text)[part];subtitle.hidden=!subtitle.hidden;}));const rate=lineIcon(button('','慢速朗讀',()=>{slow=!slow;rate.setAttribute('aria-pressed',String(slow));if(speaking&&!paused)speak();}),'M9 2h6 M12 2v3 M18 6l2-2 M12 9v5l3 2 M20 14a8 8 0 1 1-16 0 8 8 0 0 1 16 0');rate.setAttribute('aria-pressed',String(slow));header.append(rate);
 const prev=button('‹','上一頁',()=>turn(-1));prev.disabled=page===0;const next=button('›','下一頁',()=>turn(1));next.disabled=page===books[selected].pages.length-1;const lines=chunks(p.text);
 const sentenceControls=el('div','sp-sentence-controls');sentenceControls.setAttribute('role','group');sentenceControls.setAttribute('aria-label','逐句閱讀');const count=el('span','sp-sentence-count');
 const moveSentence=(delta:number)=>{stopVoice();part=Math.max(0,Math.min(lines.length-1,part+delta));subtitle.textContent=lines[part];subtitle.hidden=false;status.textContent='';syncSentence();};
 const up=button('↑','上一句文字',()=>moveSentence(-1));const down=button('↓','下一句文字',()=>moveSentence(1));syncSentence=()=>{up.disabled=part===0;down.disabled=part===lines.length-1;count.textContent=`${part+1} / ${lines.length} 句`;};syncSentence();sentenceControls.append(up,count,down);
 footer.classList.add('sp-reader-footer');footer.append(prev,el('span','sp-title',`${page+1} / ${books[selected].pages.length} 頁`),sentenceControls,next);status.classList.add('sp-reader-status');stage.append(status);remember();}
function turn(delta:number){page=Math.max(0,Math.min(books[selected].pages.length-1,page+delta));render();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice();});window.addEventListener('pagehide',()=>{stopVoice();cleanup();});window.addEventListener('keydown',e=>{if(mode==='read'&&e.key==='ArrowRight')turn(1);if(mode==='read'&&e.key==='ArrowLeft')turn(-1);});
fetch('stories/catalog.json').then(r=>{if(!r.ok)throw Error('catalog');return r.json();}).then(data=>{books=data.books.filter((b:Book)=>b.pages?.length);if(!books.length)throw Error('empty');render();}).catch(()=>{root.replaceChildren(el('p','sp-error','故事暫時無法載入，請稍後再試。'));const back=el('a','sp-icon','←');back.href='index.html';back.setAttribute('aria-label','回首頁');root.append(back);});
