import * as THREE from 'three';
import './style.css';
type Page={id:string;title:string;text:string;image:string};
type Book={id:string;title:string;cover:string;video:string;pages:Page[]};
const root=document.querySelector<HTMLElement>('#story-app')!;
root.style.backgroundImage="radial-gradient(ellipse at 50% 42%,#34436988,transparent 65%),url('images/experiments/shared-classroom/v1/classroom.png')";
let books:Book[]=[],selected=0,page=0,mode:'shelf'|'read'|'video'='shelf',cleanup=()=>{},speaking=false,slow=false,epoch=0;
let part=0,paused=false;
let playbackButton:HTMLButtonElement|undefined;
function syncPlayback(){if(!playbackButton)return;const active=speaking&&!paused;playbackButton.textContent=active?'Ⅱ':'▶';const label=active?'暫停朗讀':paused?'繼續朗讀':'播放朗讀';playbackButton.setAttribute('aria-label',label);playbackButton.title=label;playbackButton.setAttribute('aria-pressed',String(active));}
function togglePlayback(){if(speaking&&!paused){speechSynthesis.pause();paused=true;status.textContent='已暫停';syncPlayback();}else if(paused){speechSynthesis.resume();paused=false;status.textContent='';syncPlayback();}else speak();}
function lineIcon(b:HTMLButtonElement,paths:string){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('width','25');svg.setAttribute('height','25');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths);svg.append(path);b.replaceChildren(svg);return b;}
const chunks=(text:string)=>text.match(/[^。！？\n]+[。！？]?/g)||[text];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function stopVoice(){epoch++;window.speechSynthesis?.cancel();speaking=false;paused=false;syncPlayback();}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text=''){const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;}
function button(icon:string,label:string,action:()=>void){const b=el('button','sp-icon',icon);b.type='button';b.setAttribute('aria-label',label);b.title=label;b.onclick=action;return b;}
function saved(){try{return Math.min(books[selected].pages.length-1,Math.max(0,Number(localStorage.getItem('story-page-'+books[selected].id))||0));}catch{return 0;}}
function remember(){try{localStorage.setItem('story-page-'+books[selected].id,String(page));}catch{/* Reading works without storage. */}}
function speak(){stopVoice();if(!window.speechSynthesis){status.textContent='此裝置沒有語音，可直接閱讀字幕。';return;}const text=books[selected].pages[page].text||books[selected].title;const sentences=chunks(text);const token=epoch;speaking=true;syncPlayback();const next=(i:number)=>{if(token!==epoch||mode!=='read')return;if(i>=sentences.length){speaking=false;syncPlayback();status.textContent='換你翻頁';return;}part=i;subtitle.textContent=sentences[i];subtitle.hidden=false;const u=new SpeechSynthesisUtterance(sentences[i]);u.lang='zh-TW';u.rate=slow?.7:.9;u.onend=()=>next(i+1);u.onerror=()=>{if(token!==epoch)return;speaking=false;syncPlayback();status.textContent='語音暫時不可用，仍可自由翻頁。';};speechSynthesis.speak(u);};next(part);}
let status:HTMLElement,subtitle:HTMLButtonElement;
function render(){part=0;cleanup();cleanup=()=>{};stopVoice();root.replaceChildren();const header=el('header','sp-header');header.append(button('←',mode==='shelf'?'回首頁':'回書架',()=>{if(mode==='shelf')location.href='index.html';else{mode='shelf';render();}}),el('h1','',mode==='shelf'?'故事星球':books[selected].title));const stage=el('section','sp-stage');const footer=el('footer','sp-footer');status=el('span','sp-status');status.setAttribute('role','status');root.append(header,stage,footer);
 if(mode==='shelf'){const title=el('span','sp-title',books[selected].title);const prev=button('‹','上一本書',()=>{selected--;render();});prev.disabled=selected===0;const next=button('›','下一本書',()=>{selected++;render();});next.disabled=selected===books.length-1;footer.append(prev,title,next);stage.append(el('div','sp-caption','點書背，打開故事'));shelf(stage,books[selected]);return;}
 header.append(lineIcon(button('','觀看故事影片',()=>{mode=mode==='video'?'read':'video';render();}),'M4 14v-3a8 8 0 0 1 16 0v3 M4 13H3v7h4v-7H4 M20 13h1v7h-4v-7h3'));
 if(mode==='video'){const frame=document.createElement('iframe');frame.src=`https://www.youtube-nocookie.com/embed/${books[selected].video}?rel=0`;frame.title=books[selected].title+'影片';frame.allow='fullscreen; picture-in-picture';frame.allowFullscreen=true;stage.append(frame);footer.append(button('▤','進入故事閱讀',()=>{mode='read';render();}),el('span','sp-title','看完了，翻開故事書'));return;}
 stage.classList.add('is-reading');const p=books[selected].pages[page];const img=el('img','sp-page');img.src=p.image;img.alt=p.title;img.onerror=()=>{status.textContent='這頁圖片載入失敗，可翻頁或稍後再試。';};subtitle=el('button','sp-subtitle',chunks(p.text)[part]);subtitle.setAttribute('aria-label','重聽這一段');subtitle.hidden=page<2;subtitle.onclick=speak;stage.append(img,subtitle);playbackButton=button('▶','播放朗讀',togglePlayback);syncPlayback();header.append(playbackButton,button('字','顯示或隱藏文字',()=>{subtitle.textContent=chunks(p.text)[part];subtitle.hidden=!subtitle.hidden;}));const rate=lineIcon(button('','慢速朗讀',()=>{slow=!slow;rate.setAttribute('aria-pressed',String(slow));if(speaking&&!paused)speak();}),'M9 2h6 M12 2v3 M18 6l2-2 M12 9v5l3 2 M20 14a8 8 0 1 1-16 0 8 8 0 0 1 16 0');rate.setAttribute('aria-pressed',String(slow));header.append(rate);
 const prev=button('‹','上一頁',()=>turn(-1));prev.disabled=page===0;const next=button('›','下一頁',()=>turn(1));next.disabled=page===books[selected].pages.length-1;if(next.disabled)status.textContent='讀完了！你也很勇敢 ✦';const nextLine=button('▸','下一句文字',()=>{stopVoice();const lines=chunks(p.text);part=(part+1)%lines.length;subtitle.textContent=lines[part];subtitle.hidden=false;status.textContent=`${part+1} / ${lines.length} 句`;});footer.append(prev,el('span','sp-title',`${page+1} / ${books[selected].pages.length}`),nextLine,status,next);remember();}
function turn(delta:number){page=Math.max(0,Math.min(books[selected].pages.length-1,page+delta));render();}
function shelf(stage:HTMLElement,book:Book){let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{const img=el('img','sp-cover-fallback');img.src=book.cover;img.alt=book.title;const open=button('▤','打開'+book.title,()=>{mode='read';page=saved();render();});const fallback=el('div','sp-error');fallback.append(img,open);stage.append(fallback);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.className='sp-canvas';renderer.domElement.setAttribute('aria-hidden','true');stage.prepend(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,50);camera.position.set(0,.1,8.5);scene.add(new THREE.HemisphereLight(0xd8f6ff,0x493455,2.8));const light=new THREE.DirectionalLight(0xffefd0,3);light.position.set(-3,4,5);scene.add(light);
 const group=new THREE.Group();scene.add(group);const textures:THREE.Texture[]=[];const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=768;const ctx=canvas.getContext('2d')!;const bg=ctx.createLinearGradient(0,0,1024,768);bg.addColorStop(0,'#23265a');bg.addColorStop(1,'#543670');ctx.fillStyle=bg;ctx.fillRect(0,0,1024,768);ctx.strokeStyle='#e6c47b';ctx.lineWidth=7;ctx.strokeRect(38,38,948,692);ctx.lineWidth=2;ctx.strokeRect(55,55,914,658);ctx.fillStyle='#ffdfa1';ctx.textAlign='center';ctx.font='60px serif';ctx.fillText('✦',512,275);ctx.font='bold 54px sans-serif';ctx.fillText(book.title,512,405);ctx.font='26px sans-serif';ctx.fillText('STORY PLANET',512,515);const back=new THREE.CanvasTexture(canvas);back.colorSpace=THREE.SRGBColorSpace;textures.push(back);
 const gold=new THREE.MeshStandardMaterial({color:0xe2b95d,metalness:.45,roughness:.4}),paper=new THREE.MeshStandardMaterial({color:0xffefcf,roughness:.8}),backMat=new THREE.MeshStandardMaterial({map:back,roughness:.6});const coverMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.6});
 const pages=new THREE.Mesh(new THREE.BoxGeometry(3.12,2.3,.23),paper);group.add(pages);
 for(const z of [-.16,.16]){const cover=new THREE.Mesh(new THREE.BoxGeometry(3.3,2.475,.07),[gold,gold,gold,gold,z>0?coverMat:backMat,backMat]);cover.position.z=z;group.add(cover);}
 const spine=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,2.475,20),gold);spine.position.x=-1.6;group.add(spine);
 for(let i=0;i<9;i++){const line=new THREE.Mesh(new THREE.BoxGeometry(3.12,.008,.003),gold);line.position.set(0,-1.14+i*.285,.117);group.add(line);}
 let disposed=false,raf=0,last=0,selectAt:number|null=null;const start=performance.now();group.rotation.set(.08,Math.PI+.3,-.07);
 new THREE.TextureLoader().load(book.cover,t=>{if(disposed){t.dispose();return;}t.colorSpace=THREE.SRGBColorSpace;textures.push(t);coverMat.map=t;coverMat.needsUpdate=true;renderer.render(scene,camera);},undefined,()=>{status.textContent='封面暫未載入，仍可開啟故事。';});
 const overlay=el('div','sp-shelf-picker');const hit=el('button','sp-book-hit','打開'+book.title);hit.setAttribute('aria-label','點書背，打開'+book.title);overlay.append(hit);stage.append(overlay);hit.onclick=()=>{if(selectAt!==null)return;hit.disabled=true;selectAt=performance.now();stage.querySelector('.sp-caption')!.textContent=book.title;if(reduced){group.rotation.set(0,0,0);renderer.render(scene,camera);}};
 const resize=()=>{const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.position.z=camera.aspect<1?12:8.5;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(stage);resize();
 const tick=(now:number)=>{if(disposed)return;raf=requestAnimationFrame(tick);if(document.hidden||now-last<33)return;last=now;if(selectAt!==null){const t=Math.min(1,(now-selectAt)/1000),ease=t*t*(3-2*t);group.rotation.y=(Math.PI+.3)*(1-ease);group.rotation.z=-.07*(1-ease);group.rotation.x=.08*(1-ease);group.position.y=0;group.scale.setScalar(1+.13*ease);if(now-selectAt>1750){mode='read';page=saved();render();return;}}else if(!reduced){group.position.y=Math.sin((now-start)/1300)*.09;group.rotation.z=-.07+Math.sin((now-start)/1700)*.025;}renderer.render(scene,camera);};raf=requestAnimationFrame(tick);
 cleanup=()=>{disposed=true;cancelAnimationFrame(raf);ro.disconnect();scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});[gold,paper,backMat,coverMat].forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();};}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice();});window.addEventListener('pagehide',()=>{stopVoice();cleanup();});window.addEventListener('keydown',e=>{if(mode==='read'&&e.key==='ArrowRight')turn(1);if(mode==='read'&&e.key==='ArrowLeft')turn(-1);});
fetch('stories/catalog.json').then(r=>{if(!r.ok)throw Error('catalog');return r.json();}).then(data=>{books=data.books.filter((b:Book)=>b.pages?.length);if(!books.length)throw Error('empty');render();}).catch(()=>{root.replaceChildren(el('p','sp-error','故事暫時無法載入，請稍後再試。'));const back=el('a','sp-icon','←');back.href='index.html';back.setAttribute('aria-label','回首頁');root.append(back);});
