import type {ReadingLevel} from './dragon-text';
const rows=[
 ['A quiet tile','A tile is by the bed.|Gail looks closely.','Gail finds a blue tile by her bed.|It is not shining yet.','Beside her bed, Gail notices a small blue tile.|She bends closer to look at its smooth surface.','床旁有一片磁磚。|瑜瑜仔細看。','瑜瑜在床旁發現藍磁磚。|它還沒有發光。','床旁，瑜瑜注意到一片藍色小磁磚。|她彎身靠近，看它光滑的表面。'],
 ['A doorway of light','The tile shines!|A new way opens.','The tile begins to shine.|Blue squares make a doorway.','Only after Gail looks closely does the tile begin to glow.|Small blue squares rise from it and form a doorway to a pottery cottage.','磁磚發光了！|一條新路打開了。','磁磚開始發光。|藍色方塊排成一道門。','瑜瑜靠近仔細看後，磁磚才開始發光。|藍色小方塊從磁磚升起，拼出通往陶藝小屋的門。'],
 ['Meet Bear','Here is Bear.|An adult works here.','Gail meets Bear in a pottery room.|An adult makes things from clay.','Inside the cottage, Gail meets a young bear and an adult potter.|The potter shapes clay into useful things, then fires them in a kiln.','這是小熊。|一位大人在這裡工作。','瑜瑜在陶藝屋遇見小熊。|一位大人用陶土做東西。','屋內，瑜瑜遇見小熊和一位成年陶藝師。|陶藝師把陶土捏成有用的物品，再送進窯裡燒製。'],
 ['On the shelf','Look at the shelf.|Bear likes this one.','A blue pot sits on the shelf.|Bear wants a closer look.','A finished pot with a blue band rests on a low shelf.|Bear likes its pattern and wants to see the other side.','看看架子。|小熊喜歡這一個。','藍色陶盆放在架子上。|小熊想靠近看。','低矮架子上放著一個有藍色飾帶的陶盆。|小熊喜歡它的花紋，想看看另一面。'],
 ['A little reach','Bear starts to reach.|His arm is close.','Bear reaches across the shelf.|His elbow comes close to the pot.','Bear reaches across the low shelf for a small tool.|He does not notice how close his elbow is to the finished pot.','小熊伸出手。|手臂靠得很近。','小熊伸手越過架子。|手肘靠近陶盆。','小熊伸手越過低架子拿小工具。|牠沒注意到手肘已經很靠近做好的陶盆。'],
 ['Bump and crack','Bump!|Crack! It is broken.','Bear bumps the pot.|It falls with a crack.|Now it is broken.','Bear bumps the pot with his elbow, and it tips over the edge.|It hits the floor with a sharp crack and breaks into several pieces.','碰！|喀啦！它破了。','小熊碰倒陶盆。|它落下，喀啦一聲。|現在它破了。','小熊的手肘碰到陶盆，它翻過架子邊緣。|陶盆落地，發出清脆的碎裂聲，裂成好幾片。'],
 ['Stand back','A broken piece.|Stand back, Bear.','A piece has a sharp edge.|Gail asks Bear to stand back.','Gail sees that a broken piece has a sharp edge.|She asks Bear to step back and leave the fragments where they are.','一塊碎片。|小熊，退後。','一塊碎片邊緣很尖。|瑜瑜請小熊退後。','瑜瑜看見一塊碎片的邊緣很尖。|她請小熊退後，把碎片留在原地。'],
 ['Hidden from view','Bear wants to hide it.|He pulls a curtain.','Bear pulls a low curtain across the mess.|He does not touch the pieces.','While the potter is in the next room, Bear pulls a low curtain across the fallen pieces.|He does not pick them up, but he hopes hiding them will make the problem disappear.','小熊想藏起來。|牠拉上簾子。','小熊拉上低簾子，遮住凌亂的地方。|牠沒有碰碎片。','陶藝師在隔壁時，小熊拉上低簾子，遮住掉落的碎片。|牠沒有撿起來，卻希望藏起來就能讓問題消失。'],
 ['A worried face','Bear is worried.|He looks away.','Bear looks worried.|He cannot enjoy the clay now.','Bear keeps glancing at the curtain with a worried face.|Even the soft clay on the bench cannot hold his attention.','小熊很擔心。|牠把頭轉開。','小熊看起來很擔心。|牠現在無心玩陶土。','小熊滿臉擔心，不停看向簾子。|連工作檯上柔軟的陶土都無法吸引牠的注意。'],
 ['Time to tell','Gail sits nearby.|You can tell me.','Gail sits beside Bear.|“You can tell me what happened.”','Gail sits near Bear without pulling the curtain aside.|“You can tell me what happened,” she says, and gives him time to answer.','瑜瑜坐在附近。|你可以告訴我。','瑜瑜坐在小熊旁。|「你可以告訴我發生什麼事。」','瑜瑜坐在小熊附近，沒有拉開簾子。|「你可以告訴我發生什麼事。」她說，留時間讓牠回答。'],
 ['The truth','I bumped it.|That is the truth.','“I bumped it,” says Bear.|He tells Gail the truth.','Bear takes a breath and tells Gail the truth.|“I bumped the pot, and then I hid the pieces because I was frightened.”','是我碰倒的。|這是事實。','「是我碰倒的。」小熊說。|牠告訴瑜瑜實話。','小熊吸口氣，告訴瑜瑜實話。|「我碰倒陶盆，然後因為害怕，把碎片藏了起來。」'],
 ['Tell the potter','Tell the adult.|Gail comes too.','Bear goes to tell the adult.|Gail walks beside him.','Gail offers to stand beside Bear while he speaks to the potter.|Bear agrees; telling the person whose work was broken is the next step.','告訴大人。|瑜瑜也一起去。','小熊去告訴大人。|瑜瑜走在牠旁邊。','瑜瑜願意陪小熊站在一起，向陶藝師說明。|小熊同意了；下一步，是告訴作品被弄壞的人。'],
 ['An honest answer','I did it.|I will be honest.','Bear gives an honest answer.|He says how the pot broke.','The potter asks what happened, and Bear gives an honest answer.|He explains both the accident and his choice to hide it, without blaming anyone else.','是我做的。|我要誠實。','小熊誠實回答。|牠說出陶盆怎麼破的。','陶藝師問發生什麼事，小熊誠實回答。|牠說明意外，也承認自己選擇藏起來，沒有怪別人。'],
 ['More than sorry','I am sorry.|What can I do?','“I am sorry,” says Bear.|“What can I do now?”','“I am sorry I broke your work and hid it,” Bear says.|He asks what he can do next, knowing that an apology does not put the pot back together.','對不起。|我能做什麼？','「對不起。」小熊說。|「現在我能做什麼？」','「對不起，我弄壞你的作品，還藏起來。」小熊說。|牠問接下來能做什麼，也知道道歉不會讓陶盆自動復原。'],
 ['Gloves first','The adult has gloves.|We stay back.','The potter puts on thick gloves.|The children stay back.','The potter thanks Bear for telling her and puts on protective gloves.|She asks both children to keep clear while she handles the sharp pieces.','大人戴著手套。|我們退後。','陶藝師戴上厚手套。|孩子們站遠一點。','陶藝師謝謝小熊願意說實話，並戴上防護手套。|她處理尖銳碎片時，請兩個孩子都站遠一點。'],
 ['Sweep it safely','The adult will sweep.|Bear watches.','The potter sweeps the small bits into a pan.|Bear waits at a safe distance.','Using a brush and dustpan, the potter sweeps up the small bits.|Bear waits at a safe distance instead of trying to collect sharp pieces with his paws.','大人來清掃。|小熊看著。','陶藝師把小碎片掃進畚箕。|小熊在安全距離等待。','陶藝師用刷子和畚箕掃起小碎屑。|小熊在安全距離等待，不用小手去撿尖銳碎片。'],
 ['A different repair','Can we repair it?|A new plan!','The potter cannot repair this pot for use.|She has a new plan for the smooth pieces.','The potter explains that the cracked pot cannot safely be used as before.|After making selected edges smooth, she proposes a different kind of repair: a decorative picture.','能修補嗎？|有新計畫了！','陶藝師無法把陶盆修到能再使用。|她有個利用光滑碎片的新計畫。','陶藝師解釋，破裂的陶盆無法像以前一樣安全使用。|她把選好的碎片邊緣磨平後，提議換一種修補方式：做裝飾圖畫。'],
 ['Piece by piece','One smooth piece.|A mosaic!','They arrange smooth pieces in a mosaic.|The adult adds the glue.','With the edges already made safe, Bear and Gail arrange the pieces into a heart mosaic.|The potter applies the glue and helps them press each piece into place.','一塊光滑碎片。|拼貼畫！','他們把光滑碎片排成拼貼。|大人來上膠。','邊緣已處理安全後，小熊和瑜瑜把碎片排成愛心拼貼。|陶藝師上膠，幫他們把每片壓在正確的位置。'],
 ['Keep the promise','The mosaic is ready.|Bear tells the truth.','The mosaic goes on the shelf.|Bear promises to tell the truth next time.','When the glue is dry, they display the mosaic on the shelf.|Bear understands that being honest means telling what happened and helping with what comes next.','拼貼做好了。|小熊說實話。','拼貼放上架子。|小熊答應下次說實話。','膠乾後，他們把拼貼展示在架上。|小熊明白，誠實就是說出發生的事，並幫忙處理接下來的事情。'],
 ['Home with a tile','Gail is home.|The tile is quiet.','Gail comes home with the blue tile.|She remembers Bear’s honest words.','Back in her familiar room, Gail sets the blue tile beside her bed.|It reminds her that hiding a mistake cannot repair it, but an honest first word can begin the work.','瑜瑜回家了。|磁磚安靜了。','瑜瑜帶著藍磁磚回家。|她記得小熊誠實的話。','回到熟悉的房間，瑜瑜把藍磁磚放在床旁。|它提醒她，隱藏錯誤無法修補，但誠實的第一句話能開啟改變。']
];
export const bearTitles=rows.map(r=>r[0]);
export const bearText=rows.map(r=>Object.fromEntries(['A','B','C'].map((l,i)=>[l,r[i+1].split('|')])) as Record<ReadingLevel,string[]>);
export function bearChinese(page:number,level:ReadingLevel){return rows[page][4+{A:0,B:1,C:2}[level]].split('|');}
