export function createBearEffects(world:HTMLElement,page:number,soundEnabled:boolean){
 let disposed=false;const animations=new Set<Animation>(),nodes:HTMLElement[]=[];let context:AudioContext|undefined;let breaking=false,repairing=false;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const obj=(id:string)=>world.querySelector<HTMLElement>(`[data-object="${id}"]`);
 function anim(n:HTMLElement,frames:Keyframe[],duration:number,delay=0){const a=n.animate(frames,{duration:reduced?100:duration,delay:reduced?0:delay,fill:'forwards',easing:'ease-in-out'});animations.add(a);return a;}
 function clear(){animations.forEach(a=>a.cancel());animations.clear();nodes.splice(0).forEach(n=>n.remove());}
 function crack(){if(!soundEnabled||disposed)return;context??=new AudioContext();void context.resume();const t=context.currentTime;for(const f of [940,1530,2280]){const o=context.createOscillator(),g=context.createGain();o.type='triangle';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*.62,t+.16);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g).connect(context.destination);o.start(t);o.stop(t+.25);}}
 function portal(){clear();const tile=obj('tile');if(!tile)return;anim(tile,[{filter:'none'},{filter:'drop-shadow(0 0 22px #8be6e3)'}],1000,700);for(let i=0;i<16;i++){const n=document.createElement('i');n.className='bear-light-tile';tile.append(n);nodes.push(n);anim(n,[{opacity:0,translate:'0 0'},{opacity:1,offset:.3},{opacity:0,translate:`${(i%4-1.5)*45}px ${-80-Math.floor(i/4)*38}px`,rotate:`${i*15}deg`}],2200,1000+i*45);}if(page===1){const bg=document.createElement('img');bg.className='bear-arrival';bg.src='images/story/bear-v1/workshop.png';bg.alt='藍光連向陶藝屋';world.append(bg);nodes.push(bg);anim(bg,[{opacity:0},{opacity:1}],1400,2600);}}
 function visible(n:HTMLElement,show:boolean){n.style.visibility=show?'visible':'hidden';n.setAttribute('aria-hidden',String(!show));if(n instanceof HTMLButtonElement)n.disabled=!show;}
 // A tracked clock preserves the 200 ms empty interval, including when paused.
 function replaceAfterGap(from:HTMLElement,to:HTMLElement,done:()=>void){visible(from,false);visible(to,false);const clock=from.animate([{},{}],{duration:200});animations.add(clock);clock.onfinish=()=>{if(disposed)return;visible(to,true);done();};}
 const pieces=obj('piece'),materials=obj('repair'),finished=obj('mosaic');
 if(page===5&&pieces)visible(pieces,false);
 if(page===17&&finished)visible(finished,false);
 function fall(){if(breaking)return;const pot=obj('pot');if(!pot||!pieces)return;clear();breaking=true;visible(pieces,false);visible(pot,true);const distance=(pieces.offsetTop-pot.offsetTop);const a=anim(pot,[{translate:'0 0',rotate:'0deg'},{translate:'25px 0',rotate:'24deg',offset:.3},{translate:`35px ${distance}px`,rotate:'90deg'}],1200);a.onfinish=()=>{if(disposed)return;crack();replaceAfterGap(pot,pieces,()=>{breaking=false;});const face=obj('bear')?.querySelector('img');if(face)face.src='images/story/bear-v1/bear-worried.png';};}
 function reach(){const bear=obj('bear');if(bear)anim(bear,[{translate:'0 0'},{translate:'-24px 0',offset:.5},{translate:'0 0'}],1500);}
 function hide(){const curtain=obj('curtain');if(curtain)anim(curtain,[{translate:'30% 0',opacity:.25},{translate:'0 0',opacity:1}],1100);}
 function sweep(){const brush=obj('sweep');if(brush)anim(brush,[{translate:'0 0',rotate:'0deg'},{translate:'-50px 0',rotate:'-12deg',offset:.5},{translate:'0 0',rotate:'0deg'}],1500);if(pieces)anim(pieces,[{opacity:1},{opacity:0}],700,1200);}
 function repair(){if(!finished||repairing)return;if(!materials){anim(finished,[{scale:'.95'},{scale:'1'}],500);return;}clear();repairing=true;visible(finished,false);visible(materials,true);const assembly=anim(materials,[{rotate:'0deg'},{rotate:'-3deg',offset:.5},{rotate:'0deg'}],700);assembly.onfinish=()=>{if(disposed)return;replaceAfterGap(materials,finished,()=>{repairing=false;});};}
 function interact(id:string){if(disposed)return;if(page<2){portal();return;}if(page===4&&(id==='bear'||id==='reach'))reach();if(page===5&&['pot','bump','crack','broken'].includes(id))fall();if(page===7||page===8)hide();if(id==='sweep')sweep();if(page>=17&&['mosaic','piece','repair'].includes(id))repair();}
 return {interact,sentence(index:number,_text:string){if(index!==0)return;if(page<2)portal();else if(page===4)reach();else if(page===5)fall();else if(page===7)hide();else if(page===15)sweep();else if(page===17)repair();},playback(running:boolean,paused:boolean){animations.forEach(a=>{if(paused||!running)a.pause();else a.play();});if(context){if(paused||!running)void context.suspend();else void context.resume();}},sound(enabled:boolean){soundEnabled=enabled;if(!enabled&&context)void context.suspend();},dispose(){disposed=true;clear();void context?.close();}};
}
