import type {ReadingLevel} from './dragon-text';
const rows=[
 ['Under the lid','A little chest.|Gail lifts the lid.','Gail finds a little chest.|She lifts the lid.|What is inside?','A small wooden chest waits beside Gail’s bed.|She carefully lifts the lid and finds a brass bell tucked inside.','一個小寶箱。|瑜瑜掀起箱蓋。','瑜瑜找到小寶箱。|她掀起箱蓋。|裡面有什麼？','床旁放著一個小木寶箱。|瑜瑜小心掀開箱蓋，發現裡面藏著一個黃銅鈴鐺。'],
 ['A chime in the mist','A soft chime.|Mist comes out.','Gail lifts the bell.|It makes a soft chime.|Mist rolls out of the chest.','Gail lifts the bell and gives it a gentle shake.|A clear chime rings out, and silver mist rises around it, opening a way to a grassy hill.','一聲輕響。|霧冒出來。','瑜瑜拿起鈴鐺。|鈴鐺輕輕響。|霧從寶箱湧出。','瑜瑜拿起鈴鐺，輕輕搖一下。|清亮的鈴聲響起，銀霧圍著鈴鐺升起，打開通往草地山丘的路。'],
 ['A floating friend','A little cloud.|It can float.','Gail sees a little cloud.|It can float above the grass.','On the hill, Gail meets a small cloud floating above the grass.|Below it lies a careful spiral of orange and green leaves.','一朵小雲。|牠會飄浮。','瑜瑜看見小雲朵。|牠能飄浮在草地上。','山丘上，瑜瑜遇見一朵飄浮在草地上方的小雲。|牠下面是用橘色和綠色葉片細心排好的螺旋。'],
 ['A breeze arrives','A breeze comes.|The leaves move.','A breeze crosses the hill.|The leaves begin to move.','A breeze slips through the trees and across the hill.|The edges of the leaf spiral begin to lift from the ground.','微風吹來。|葉片動了。','微風吹過山丘。|葉片開始移動。','微風吹過樹間，越過山丘。|葉片螺旋的邊緣開始離開地面。'],
 ['Scattered work','The leaves scatter.|Oh, no!','The leaves scatter across the grass.|The spiral is gone.','A stronger gust scatters the leaves across the grass.|Cloud watches the pattern it worked so hard to make come apart.','葉片散開了。|哎呀！','葉片散落在草地上。|螺旋不見了。','一陣較強的風吹得葉片散落草地。|小雲朵看著自己辛苦排好的圖案散掉了。'],
 ['Round and round','Spin, spin!|The leaves spin.','The leaves spin in the air.|Cloud tries to catch them.','The loose leaves spin beyond Cloud’s reach.|The faster Cloud rushes after them, the harder it becomes to arrange anything.','轉呀，轉呀！|葉片在旋轉。','葉片在空中旋轉。|小雲朵試著接住。','散開的葉片旋轉著，飄到小雲朵搆不到的地方。|牠越急著追趕，就越難把任何葉片排好。'],
 ['A clap of thunder','Thunder!|Cloud is dark.','Cloud turns dark.|A clap of thunder shakes the air.','Cloud grows darker, and a clap of thunder rolls across the hill.|Gail steps back and gives her new friend some space.','打雷了！|小雲朵變暗。','小雲朵變暗。|一聲雷響震動空氣。','小雲朵越來越暗，一聲雷響滾過山丘。|瑜瑜退後，留一點空間給新朋友。'],
 ['A loud rumble','A rumble.|It is loud.','The rumble is loud.|Gail waits nearby.','Another loud rumble follows the first.|Gail stays nearby without shouting over it, waiting until Cloud can hear her.','一陣隆隆聲。|聲音很大。','隆隆聲很大。|瑜瑜在附近等。','第一聲雷後又傳來響亮的隆隆聲。|瑜瑜留在附近，沒有提高聲音蓋過雷聲，而是等小雲朵能聽見她。'],
 ['Angry inside','“I am angry!”|Gail stays.','“I am angry!” says Cloud.|Gail stays with her friend.','“I am angry!” Cloud says when the rumble fades.|Gail does not ask it to smile or pretend nothing happened.','「我很生氣！」|瑜瑜留下來。','「我很生氣！」小雲朵說。|瑜瑜陪著朋友。','隆隆聲漸弱後，小雲朵說：「我很生氣！」|瑜瑜沒有要牠笑，也沒有要牠假裝沒事。'],
 ['Upset about the work','“I am upset.”|“My work is gone.”','“I am upset,” says Cloud.|“I worked hard on that spiral.”','“I am upset because my work blew away,” Cloud explains.|Gail sits down to hear what the pattern meant to her friend.','「我很難受。」|「我的作品不見了。」','「我很難受，」小雲朵說。|「那個螺旋是我辛苦排的。」','「我的作品被吹走，所以我很難受，」小雲朵解釋。|瑜瑜坐下，聽朋友說這個圖案對牠有什麼意義。'],
 ['Name the feeling','Name it.|“Angry and upset.”','Gail helps Cloud name it.|“Angry and upset,” says Cloud.','Gail helps Cloud name the feelings without judging them.|“Angry about the wind, and upset about my work,” Cloud says.','說出感受。|「生氣，也難受。」','瑜瑜幫小雲朵說出感受。|「生氣，也難受，」小雲朵說。','瑜瑜幫小雲朵說出感受，不去批評。|小雲朵說：「我對風很生氣，也為作品感到難受。」'],
 ['A small pause','Take a pause.|We can wait.','“Let’s take a pause,” says Gail.|The leaves can wait.','Gail suggests a short pause before they do anything else.|They let the leaves rest where they landed and stop trying to chase every one.','停一小下。|我們可以等。','「我們停一小下，」瑜瑜說。|葉片可以等。','瑜瑜提議，先停一小下，再做其他事。|她們讓葉片留在落下的位置，不再試著追趕每一片。'],
 ['Breathe together','Breathe in.|Breathe out.','Gail and Cloud breathe in.|Then they breathe out together.','Gail takes an easy breath in and slowly lets it out.|Cloud tries with her, making a little puff that turns the pinwheel.','吸氣。|吐氣。','瑜瑜和小雲朵吸氣。|接著一起吐氣。','瑜瑜輕鬆吸一口氣，再慢慢吐出。|小雲朵跟著試，輕輕吹出的氣讓紙風車轉動。'],
 ['A slow turn','A slow turn.|In and out.','The pinwheel makes a slow turn.|They try one more breath.','They watch the pinwheel make a slow turn, then rest.|There is no race to feel better; they can take another easy breath when they are ready.','慢慢轉一圈。|吸氣，吐氣。','紙風車慢慢轉一圈。|她們再試著呼吸一次。','她們看紙風車慢慢轉一圈，然後停下。|感覺好一點不是比賽；準備好時，再輕鬆呼吸一次就好。'],
 ['A little calmer','A calm moment.|Not all better yet.','Cloud has a calm moment.|It is still upset about the work.','The rumble eases, and Cloud has a calm moment.|It still cares about the broken pattern, but now it has room to choose what to do.','平靜的一刻。|還沒有完全好。','小雲朵有了平靜的一刻。|牠仍為作品感到難受。','隆隆聲減弱，小雲朵有了平靜的一刻。|牠仍在意散掉的圖案，但現在能想一想接下來要做什麼。'],
 ['Say what you need','“I need help.”|“Please stay.”','“I need help,” says Cloud.|“Will you stay with me?”','Cloud tells Gail what it needs instead of trying to manage alone.|“Please stay and help me begin again,” it asks.','「我需要幫忙。」|「請留下來。」','「我需要幫忙，」小雲朵說。|「妳願意陪我嗎？」','小雲朵把需要的幫助告訴瑜瑜，不再獨自硬撐。|牠問：「請留下來，幫我重新開始，好嗎？」'],
 ['Begin again','We can try again.|One leaf, then two.','They begin again.|Gail puts one leaf beside another.','Together, they begin again with the leaves that landed nearby.|The new spiral does not have to match the old one exactly.','我們可以再試一次。|一片，再一片。','她們重新開始。|瑜瑜把一片葉子放在另一片旁。','她們用落在附近的葉片，一起重新開始。|新的螺旋不必和舊的一模一樣。'],
 ['A gentle breeze','A gentle breeze.|The spiral stays.','Cloud makes a gentle breeze.|This time the spiral stays in place.','Cloud tries a gentle breeze while Gail sets down the last leaf.|They choose a sheltered patch near the wall, so their new work can stay in place.','一陣柔和的風。|螺旋留住了。','小雲朵吹出柔和的風。|這次，螺旋留在原位。','瑜瑜放下最後一片葉子時，小雲朵試著吹出柔和的風。|她們選了牆旁避風的位置，讓新作品能好好留著。'],
 ['Room for every feeling','A soft shower.|We can begin again.','A soft shower falls on the grass.|Cloud knows it can pause and ask for help.','A soft shower settles the dust around their finished spiral.|Cloud knows strong feelings may return, and it can pause, name them, and ask for help again.','一場輕柔的雨。|我們可以重新開始。','輕柔的雨落在草地上。|小雲朵知道，自己可以停一下，再請人幫忙。','輕柔的雨讓完成的螺旋旁揚塵沉下。|小雲朵知道，強烈的感受可能再來，而自己可以停一下、說出感受，再次請人幫忙。'],
 ['The quiet chime','A quiet chime.|Gail is home.','Gail is home again.|The quiet chime reminds her to pause.','Back in her familiar room, Gail sets the bell beside the chest.|Its quiet chime reminds her that a pause can make space for the next small choice.','一聲輕響。|瑜瑜回家了。','瑜瑜又回到家。|輕輕的鈴聲提醒她停一下。','回到熟悉的房間，瑜瑜把鈴鐺放在寶箱旁。|輕輕的鈴聲提醒她：停一下，能留出空間，做下一個小選擇。']
];
export const cloudTitles=rows.map(r=>r[0]);
export const cloudText=rows.map(r=>({A:r[1].split('|'),B:r[2].split('|'),C:r[3].split('|')}));
export function cloudChinese(page:number,level:ReadingLevel){return rows[page][{A:4,B:5,C:6}[level]].split('|');}
