/** Scene-owned animations and sounds; all replacement states are mutually exclusive. */
export function createCloudEffects(world:HTMLElement,page:number,soundEnabled:boolean){
 let disposed=false,busy=false;let context:AudioContext|undefined;
 const animations=new Set<Animation>(),nodes:HTMLElement[]=[];const sources=new Set<AudioScheduledSourceNode>();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const obj=(id:string)=>world.querySelector<HTMLElement>(`[data-object="${id}"]`);
 const leaves=Array.from({length:6},(_,i)=>obj('leaf'+i)).filter(Boolean) as HTMLElement[];
 const pattern=obj('pattern'),bell=obj('bell'),lid=obj('lid');
 function visible(n:HTMLElement|undefined|null,show:boolean){if(!n)return;n.style.visibility=show?'visible':'hidden';n.setAttribute('aria-hidden',String(!show));if(n instanceof HTMLButtonElement)n.disabled=!show;}
 function animate(n:HTMLElement,frames:Keyframe[],duration:number,delay=0){const a=n.animate(frames,{duration:reduced?100:duration,delay:reduced?0:delay,fill:'forwards',easing:'ease-in-out'});animations.add(a);return a;}
 function clock(n:HTMLElement,ms:number,done:()=>void){const a=n.animate([{},{}],{duration:ms});animations.add(a);a.onfinish=()=>{if(!disposed)done();};}
 function clear(){sources.forEach(s=>{try{s.stop();}catch{}});sources.clear();animations.forEach(a=>{a.onfinish=null;a.cancel();});animations.clear();nodes.splice(0).forEach(n=>n.remove());busy=false;}
 function audio(){if(!soundEnabled||disposed)return;context??=new AudioContext();void context.resume();return context;}
 function chime(){const c=audio();if(!c)return;const t=c.currentTime;for(const [f,gain] of [[880,.035],[1320,.014],[1760,.008]]){const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+1.3);o.connect(g).connect(c.destination);sources.add(o);o.onended=()=>sources.delete(o);o.start(t);o.stop(t+1.4);}}
 function noise(kind:'wind'|'thunder',gentle=false){const c=audio();if(!c)return;const duration=kind==='wind'?2.2:1.4;const buffer=c.createBuffer(1,c.sampleRate*duration,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1);const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=kind==='thunder'?190:650;const t=c.currentTime;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(gentle?.012:kind==='thunder'?.09:.035,t+.16);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(filter).connect(gain).connect(c.destination);sources.add(source);source.onended=()=>sources.delete(source);source.start();source.stop(t+duration);}
 function rings(){if(!bell)return;chime();animate(bell,[{rotate:'-12deg'},{rotate:'12deg',offset:.3},{rotate:'-8deg',offset:.6},{rotate:'0deg'}],650);for(let i=0;i<3;i++){const ring=document.createElement('i');ring.className='cloud-chime-ring';bell.append(ring);nodes.push(ring);animate(ring,[{opacity:.8,scale:'.3'},{opacity:0,scale:'2.8'}],1000,i*180);}}
 function mist(){if(!bell)return;for(let i=0;i<10;i++){const puff=document.createElement('i');puff.className='cloud-mist';bell.append(puff);nodes.push(puff);animate(puff,[{opacity:0,scale:'.2',translate:'0 0'},{opacity:.85,offset:.35},{opacity:0,scale:'5',translate:`${(i%5-2)*50}px ${-70-Math.floor(i/5)*40}px`}],2300,i*90);}const arrival=document.createElement('img');arrival.src='images/story/cloud-v1/hill.png';arrival.alt='霧後的雲朵山丘';arrival.className='cloud-arrival';world.append(arrival);nodes.push(arrival);animate(arrival,[{opacity:0},{opacity:1}],1000,1800);}
 function open(){if(busy||!lid||!bell)return;clear();busy=true;visible(bell,false);const a=animate(lid,[{translate:'0 0',rotate:'0deg'},{translate:'0 -65%',rotate:'-28deg'}],650);a.onfinish=()=>{if(disposed)return;visible(bell,true);const rise=animate(bell,[{translate:'0 0'},{translate:'0 -90%'}],600);rise.onfinish=()=>{if(disposed)return;if(page===1){rings();mist();}busy=false;};};}
 function float(){const c=obj('cloud');if(c)animate(c,[{translate:'0 0'},{translate:'0 -7px',offset:.5},{translate:'0 0'}],2400);}
 function wind(gentle=false){if(busy)return;noise('wind',gentle);if(page===4&&pattern){visible(pattern,false);leaves.forEach(n=>visible(n,false));clock(pattern,200,()=>{leaves.forEach(n=>visible(n,true));blow(gentle);});}else blow(gentle);}
 function blow(gentle:boolean){leaves.forEach((n,i)=>{animate(n,[{translate:'0 0',rotate:'0deg'},{translate:`${gentle?8:30+i*4}px ${gentle?-3:-35-i*4}px`,rotate:`${gentle?8:90+i*20}deg`,offset:.5},{translate:gentle?'0 0':`${14+i*4}px 0`,rotate:gentle?'0deg':`${20+i*15}deg`}],gentle?2700:1500,i*55);});if(!leaves.length&&pattern)animate(pattern,[{rotate:'0deg'},{rotate:gentle?'.4deg':'1deg',offset:.5},{rotate:'0deg'}],1700);}
 function thunder(){if(busy)return;busy=true;noise('thunder');const c=obj('cloud');if(c){const a=animate(c,[{filter:'brightness(1)',translate:'0 0'},{filter:'brightness(.8)',translate:'3px 0',offset:.3},{filter:'brightness(1)',translate:'0 0'}],900);a.onfinish=()=>{busy=false;};}}
 function breathe(){if(busy)return;busy=true;const c=obj('cloud'),rotor=obj('rotor')?.querySelector<HTMLElement>('img');if(c)animate(c,[{scale:'1'},{scale:'1.05',offset:.45},{scale:'1'}],3500);if(rotor){const a=animate(rotor,[{rotate:'0deg'},{rotate:'0deg',offset:.45},{rotate:'180deg'}],3500);a.onfinish=()=>{busy=false;};}else if(c)clock(c,3500,()=>{busy=false;});}
 function rebuild(){if(busy||!pattern)return;clear();busy=true;visible(pattern,false);leaves.forEach(n=>visible(n,true));leaves.forEach((n,i)=>{const dx=pattern.offsetLeft-n.offsetLeft,dy=pattern.offsetTop-n.offsetTop;animate(n,[{translate:'0 0'},{translate:`${dx+(i-2)*8}px ${dy}px`,rotate:`${i*40}deg`}],850,i*120);});clock(pattern,reduced?100:1600,()=>{leaves.forEach(n=>visible(n,false));clock(pattern,200,()=>{visible(pattern,true);busy=false;});});}
 function shower(){noise('wind',true);const c=obj('cloud');if(!c)return;for(let i=0;i<18;i++){const drop=document.createElement('i');drop.className='cloud-drop';drop.style.left=(12+(i*17)%76)+'%';c.append(drop);nodes.push(drop);animate(drop,[{opacity:0,translate:'0 0'},{opacity:.7,offset:.2},{opacity:0,translate:'0 100px'}],1300,i*65);}}
 if(page<2)visible(bell,false);if(page===4)leaves.forEach(n=>visible(n,false));if(page===16)visible(pattern,false);
 function action(){if(busy)return;clear();if(page<2)open();else if(page===19)rings();else if(page===3||page===4||page===5)wind();else if(page===6||page===7)thunder();else if(page===12||page===13)breathe();else if(page===16)rebuild();else if(page===17)wind(true);else if(page===18)shower();else float();}
 return {interact(_id:string){if(!disposed)action();},sentence(index:number,_text:string){if(index===(page===0?1:0)&&!disposed)action();},playback(running:boolean,paused:boolean){animations.forEach(a=>{if(paused||!running)a.pause();else a.play();});if(context){if(paused||!running)void context.suspend();else void context.resume();}},sound(enabled:boolean){soundEnabled=enabled;if(!enabled&&context)void context.suspend();},dispose(){disposed=true;clear();void context?.close();}};
}
