import type {ReadingLevel} from './dragon-text';
// A / B / C are teaching targets, not measured Lexile scores.
const rows=[
['The glowing acorn','An acorn!|It glows.','An acorn glows on the rug.|Gail follows its light.','An acorn glows in Gail’s familiar room.|Its golden light opens a doorway into a woodland clearing.','橡實！|它發光了。','橡實在地毯上發光。|瑜瑜跟著光走。','一顆橡實在瑜瑜熟悉的房間裡發光。|金色光芒打開一道通往林間空地的門。','acorn'],
['Meet Nori','An elf!|Hello, Nori.','Gail meets a little elf.|His name is Nori.','Gail meets a little elf named Nori beside his tree house.|He is worried about growing up and having new things to learn.','小精靈！|你好，諾里。','瑜瑜遇見小精靈。|他的名字是諾里。','瑜瑜在樹屋旁遇見小精靈諾里。|他擔心長大，也擔心要學新的事物。','elf'],
['A young bird','A young bird.|Small wings!','A young bird rests nearby.|Its wings are still small.','A young bird rests on a low branch near the house.|Nori watches its small wings and wishes it could stay just as it is.','幼鳥。|小小的翅膀！','幼鳥在附近休息。|牠的翅膀還很小。','幼鳥在屋旁低矮的樹枝上休息。|諾里看著牠的小翅膀，希望牠永遠保持現在的模樣。','young'],
['The old tree house','My old home.|I like it.','Nori likes his old tree house.|He knows every corner.','Nori shows Gail his old tree house, where everything feels familiar.|He worries that growing up might mean losing the things he loves.','我的老房子。|我喜歡它。','諾里喜歡自己的老樹屋。|每個角落他都很熟悉。','諾里帶瑜瑜看自己的老樹屋，那裡的一切都很熟悉。|他擔心長大就會失去喜歡的事物。','old'],
['Afraid of change','Change?|I am not sure.','Nori is afraid of change.|Can everything stay the same?','Nori tells Gail that change makes him nervous.|He wonders if stopping the forest will keep everything safe and familiar.','改變？|我不太確定。','諾里害怕改變。|一切可以維持原樣嗎？','諾里告訴瑜瑜，改變讓他緊張。|他想，讓森林停下來，是否就能留住安全又熟悉的一切。','change'],
['A frozen moment','Frozen!|Nothing moves.','Nori holds up the acorn.|The forest is frozen in time.','Nori uses the acorn to hold the clearing in a frozen moment.|Nothing is icy or cold, but the plants and animals can no longer change.','定住了！|什麼都不動。','諾里舉起橡實。|森林的時間定住了。','諾里用橡實把空地定在同一個瞬間。|這裡沒有冰，也不寒冷，但植物和動物都無法繼續變化。','frozen'],
['The closed bud','A bud.|Still closed.','Gail sees a pink bud.|It cannot open now.','Gail points to a pink bud beside the path.|Nori had wanted to see its petals, but the frozen moment keeps it closed.','花苞。|還是閉著。','瑜瑜看見粉紅花苞。|它現在無法打開。','瑜瑜指著小路旁的粉紅花苞。|諾里原本想看看它的花瓣，但定住的時間讓它一直閉著。','bud'],
['Not ready to eat','An unripe apple.|Not yet.','The apple is unripe.|It cannot turn red now.','The green apple is still unripe and needs more time on the tree.|With the clearing held still, it cannot become the red apple Nori was waiting for.','未熟的蘋果。|還沒好。','蘋果還沒成熟。|它現在無法變紅。','青蘋果還沒成熟，需要繼續待在樹上。|空地被定住後，它就無法變成諾里期待的紅蘋果。','unripe'],
['Wings need to grow','Wings grow.|These cannot.','The bird needs to grow.|Its wings cannot get bigger now.','The young bird needs time for its wings to grow stronger.|Nori begins to see that staying the same also keeps new possibilities out of reach.','翅膀會長大。|這雙卻不行。','小鳥需要成長。|牠的翅膀現在無法長大。','幼鳥需要時間讓翅膀長得更強壯。|諾里開始發現，一直維持原樣，也會讓新的可能無法發生。','grow'],
['Learning together','We can learn.|A little at a time.','Gail can help Nori learn.|He need not know it all today.','Gail explains that growing up does not mean knowing everything at once.|Nori can learn a little at a time and ask someone to help.','我們可以學。|一次學一點。','瑜瑜可以陪諾里學習。|他不必今天就什麼都會。','瑜瑜解釋，長大並不代表一下子什麼都懂。|諾里可以一次學一點，也可以請人幫忙。','learn'],
['Think of the seasons','A season changes.|Then another.','Gail talks about each season.|The woods change through the year.','Gail asks Nori to imagine how the woods change from one season to the next.|Different parts of the year bring different things to notice.','季節改變。|接著又一季。','瑜瑜說起每個季節。|森林會隨著一年改變。','瑜瑜請諾里想像，森林如何從一個季節走向下一個。|一年裡不同的時候，都有不同的事物可以發現。','season'],
['Imagine spring','Spring!|Buds open.','Nori imagines spring.|Small buds begin to open.','Nori imagines the woodland in spring, with small buds beginning to open.|If every moment stayed the same, he would miss these little beginnings.','春天！|花苞打開。','諾里想像春天。|小花苞開始打開。','諾里想像春天的森林，小花苞正開始打開。|如果每個瞬間都不變，他就會錯過這些小小的開始。','spring'],
['Imagine summer','Summer!|Warm days.','Nori imagines summer.|He can sit under green trees.','Next, Nori imagines summer, with warm days and leafy places to sit.|He remembers things he enjoys about this different part of the year.','夏天！|暖暖的日子。','諾里想像夏天。|他可以坐在綠樹下。','接著，諾里想像夏天，日子暖暖的，可以坐在濃密的樹葉下。|他想起一年中這個不同時節，也有他喜歡的事。','summer'],
['Imagine autumn','Autumn!|An orange leaf.','Nori imagines autumn.|Some leaves turn orange.','Nori imagines autumn and the orange leaves along the path.|The woods would look different, yet his familiar tree house could still be there.','秋天！|橘色的葉子。','諾里想像秋天。|有些葉子變橘了。','諾里想像秋天，以及小路旁橘色的葉子。|森林會變得不一樣，但熟悉的樹屋仍然可以在那裡。','autumn'],
['Imagine winter','Winter!|A quiet wood.','Nori imagines winter.|The woods have quiet days too.','Nori imagines the quiet woods in winter, with a little snow on the path.|Change can include a time to rest, as well as a time to begin.','冬天！|安靜的森林。','諾里想像冬天。|森林也有安靜的日子。','諾里想像冬天安靜的森林，小路上有一些雪。|改變可以包含休息的時候，也可以包含開始的時候。','winter'],
['The snow will melt','Snow can melt.|Then what comes?','The snow will melt one day.|Spring can come again.','Gail reminds Nori that the winter snow he imagined will melt when warmer days return.|The end of one season can make room for the next.','雪會融化。|然後呢？','雪有一天會融化。|春天可以再來。','瑜瑜提醒諾里，想像中的冬雪，會在日子回暖時融化。|一個季節的結束，可以為下一個季節留下空間。','melt'],
['Let the bud open','Allow change.|A pink bloom!','Nori lets the magic go.|The bud opens into a bloom.','Nori decides to allow change and releases the acorn’s spell.|The woodland moves again; as time passes, the bud opens into a pink bloom.','讓改變發生。|粉紅的花！','諾里放開魔法。|花苞開成一朵花。','諾里決定讓改變發生，解除橡實的魔法。|森林再次動起來；隨著時間過去，花苞開成一朵粉紅的花。','allow bloom'],
['A ripe apple','Ripe at last!|A red apple.','More days pass.|The apple is red and ripe.','More days pass in the changing woodland, and the apple becomes red and ripe.|Nori is glad that he allowed the tree the time it needed.','終於成熟了！|紅蘋果。','又過了幾天。|蘋果變紅，也成熟了。','變化中的森林又過了幾天，蘋果變紅，也成熟了。|諾里很高興，自己讓樹擁有所需的時間。','ripe'],
['Something new','A new flight!|Look at those wings.','The bird has grown.|It tries a new flight.','With time and practice, the bird grows stronger and tries a new flight.|Nori is still learning too, beside the same old tree house and a friend who helps.','新的飛行！|看那雙翅膀。','小鳥長大了。|牠嘗試新的飛行。','經過時間和練習，小鳥變得更強壯，嘗試新的飛行。|諾里也還在學習，身旁依然有老樹屋，以及願意幫忙的朋友。','new'],
['Home, one day at a time','Home again.|I can learn.','Gail is home with the acorn.|Tomorrow, she can learn something new.','The acorn’s light brings Gail back to her familiar room.|She remembers that she can welcome something new without giving up everything she loves.','回家了。|我可以學。','瑜瑜帶著橡實回到家。|明天，她可以學新的事。','橡實的光帶瑜瑜回到熟悉的房間。|她記得，迎接新的事物，不代表必須放棄所有喜愛的東西。','learn new']
];
export const elfTitles=rows.map(r=>r[0]);
export const elfWords=rows.map(r=>r[7].split(' '));
export const elfText=rows.map(r=>({A:r[1].split('|'),B:r[2].split('|'),C:r[3].split('|')}));
export function elfChinese(page:number,level:ReadingLevel){return rows[page][{A:4,B:5,C:6}[level]].split('|');}
