import type {ReadingLevel} from './dragon-text';
export const foxText:Record<ReadingLevel,string[]>[]=[
 {A:['Gail sees a drop.','It is gold.'],B:['Gail opens her book.','A gold drop shines by it.'],C:['At bedtime, Gail opens her sketchbook beside the bed.','A tiny gold drop shines on the floor, as if it wants her to follow.']},
 {A:['Look! A door!','Gail goes in.'],B:['The drop makes a door.','Gail steps through it.'],C:['The gold drop moves up the wall and paints a glowing door.','Still in her star pajamas, Gail steps through to see what is beyond it.']},
 {A:['Here is a tree.','Here is a fox.'],B:['Gail walks to a big tree.','A fox has a room inside.'],C:['A winding path leads Gail to a hollow tree.','Inside, a little fox has a room filled with paper, paint, and brushes.']},
 {A:['Fox has a brush.','The paper is blank.'],B:['Fox holds a brush.','He looks at the blank paper.','He does not start.'],C:['Fox holds his brush above a clean sheet of paper.','He wants to draw something lovely, but he is afraid of making a mistake.','His brush stays in the air.']},
 {A:['A party is coming.','Fox will draw.'],B:['There is a party soon.','Fox must draw a big picture.','He wants it to be just right.'],C:['The forest friends are having a party, and Fox has promised to make the poster.','He looks at the colorful flags above his table.','What if his picture is not good enough?']},
 {A:['Fox makes a line.','Then he stops.'],B:['Fox makes one small line.','He stops and looks at it.','“Is it wrong?” he asks.'],C:['At last, Fox draws a short blue line.','It bends a little at the end, so he stops.','“That is not how I wanted it to look,” he says.']},
 {A:['Fox feels sad.','He does not draw.'],B:['Fox rubs out the line.','He makes the paper into a ball.','Now he feels sad.'],C:['Fox rubs out the line and crumples the paper.','More paper balls gather beside the table, but there is still no poster.','He puts down his brush with a sigh.']},
 {A:['Gail sits down.','“Try one dot.”'],B:['Gail sits by Fox.','“We can try one dot,” she says.','“Just one small dot.”'],C:['Gail sits quietly beside her new friend.','“You do not need to draw the whole picture at once,” she says.','“Could we try one little dot?”']},
 {A:['Oh! The cup tips!','Blue paint spills.'],B:['Fox moves his arm.','He bumps the cup.','Blue paint spills on the paper.'],C:['As Fox reaches for his brush, his arm catches the paint cup by accident.','The cup tips over, and blue paint spreads across the paper.','Both friends pull back in surprise.']},
 {A:['“A mistake!” says Fox.','He looks down.'],B:['“It is a mistake!” says Fox.','He looks at the blue paint.','“My picture is bad.”'],C:['Fox stares at the wide blue mark.','“Now I have ruined it,” he whispers, ready to throw this sheet away too.','The party poster seems further away than ever.']},
 {A:['Gail waits.','Fox looks up.'],B:['Gail waits with Fox.','“We can look again,” she says.','Fox looks up.'],C:['Gail does not hurry Fox or tell him to stop feeling sad.','She waits beside him until he looks up.','“Shall we look at it one more time?” she asks gently.']},
 {A:['Gail turns the paper.','“A river!”'],B:['Gail turns the paper.','The blue mark looks like a river.','Fox takes a look.'],C:['Gail carefully turns the paper so they can see it from another side.','The long blue mark now looks like a winding river.','Fox leans closer; he had not noticed that before.']},
 {A:['Gail adds yellow.','The dots are flowers.'],B:['Gail adds yellow dots.','“Flowers by the river,” she says.','Then she gives Fox a turn.'],C:['Gail paints a few yellow dots beside the blue river.','“These could be flowers,” she says, then moves her hand away.','She leaves space for Fox to add an idea of his own.']},
 {A:['Fox paints a stem.','Fox smiles.'],B:['Fox adds a green stem.','He adds more stems.','Now the flowers can grow.'],C:['Fox dips his brush in green paint and adds a stem beneath a yellow flower.','Then he adds another, and a small smile appears.','For the first time today, he wants to keep drawing.']},
 {A:['A line bends.','Fox adds a leaf.'],B:['One green line bends.','Fox adds a leaf to it.','“It can be a vine!”'],C:['One green line bends more than Fox planned.','This time, he does not rub it out.','He adds leaves along the curve and turns it into a climbing vine.']},
 {A:['“A butterfly!” says Fox.','He paints wings.'],B:['Fox sees a small paint mark.','“A butterfly!” he says.','He paints two wings.'],C:['Fox notices a small orange mark near the flowers.','“I know what this can be!” he says, adding two bright wings.','His own idea has made a butterfly, and now he paints two more.']},
 {A:['Friends come in.','“Share my paint!”'],B:['Rabbit and Bear come in.','Fox will share his paint.','They help with the picture.'],C:['Rabbit and Bear arrive to see how the poster is going.','Instead of hiding the picture, Fox invites them to share his paint.','They add small details while leaving room for each other.']},
 {A:['They hang the picture.','Fox feels proud.'],B:['They hang the picture outside.','The friends all smile.','Fox feels proud of his work.'],C:['Together, the friends hang the finished poster outside the tree studio.','Fox can still see the blue spill, but now it belongs to a beautiful river.','He feels proud because they kept going and made something together.']},
 {A:['New paper. New line.','Fox will begin.'],B:['Fox takes new paper.','He makes a line.','He is ready to begin again.'],C:['Back at the table, Fox takes a fresh sheet of paper.','He does not wait for the perfect idea before making his first line.','He knows he can begin, look, and try another way as he goes.']},
 {A:['Gail is home.','She draws a line.'],B:['Gail is back in bed.','A little flower is in her book.','She draws a line and smiles.'],C:['Back in her bedroom, Gail finds a tiny painted flower in her sketchbook.','She makes a curved line beside it and wonders what it might become.','A new picture can begin with one little try.']}
];
