import type {ReadingLevel} from './dragon-text';
export const giantText:Record<ReadingLevel,string[]>[]=[
{A:['Rain falls on the village.','Gail sees a giant.'],B:['Rain patters on the village path.','Gail sees a giant beside a cottage.','He gives her a shy wave.'],C:['Rain begins as Gail reaches the village square.','Beside a cottage stands a gentle giant.','He gives Gail a shy wave with his enormous hand.']},
{A:['His umbrella is tiny.','His shoulders are wet.'],B:['The giant holds a tiny yellow umbrella.','It covers his hair, but not his shoulders.','Drip, drip! His sleeves are wet.'],C:['The giant lifts a tiny yellow umbrella above his head.','It protects his hair, but rain drips onto both shoulders.','An umbrella that fits Gail is much too small for him.']},
{A:['“Come under my umbrella!”','Gail tries to help.'],B:['“Come under mine!” Gail offers.','She lifts her red umbrella as high as she can.','It still cannot cover the giant.'],C:['Gail offers to share her red umbrella.','She stretches her arm up, but it cannot reach his head.','She needs another way to help her new friend.']},
{A:['They find a roof.','They stay dry.'],B:['Gail points to a tall workshop roof.','They step beneath it to stay dry.','“Let us think here,” she says.'],C:['Gail spots a workshop with a roof high enough for the giant.','They move underneath it before making a plan.','Out of the rain, they can think without getting wetter.']},
{A:['Gail has an idea.','“Let us work together!”'],B:['Gail looks at her small umbrella.','“What if we join many umbrellas together?”','The giant smiles at her idea.'],C:['Gail notices how two umbrellas overlap beside the door.','“Could we join lots of little umbrellas into one big cover?”','The giant smiles, ready to try her idea.']},
{A:['Their friends bring umbrellas.','They want to share.'],B:['Gail asks their friends for help.','A boy brings a blue umbrella.','“I can share mine!” he says.'],C:['Gail explains the problem to the village children.','A boy offers his blue umbrella and calls to his friends.','Soon more people arrive with something to share.']},
{A:['They count the colors.','Red, yellow, and blue!'],B:['They count the bright umbrellas.','Red, yellow, and blue make a cheerful row.','They need enough to cover two wide shoulders.'],C:['They count the umbrellas and sort them by color.','Red, yellow, and blue can become a rainbow pattern.','Gail checks that they have enough for a wide cover.']},
{A:['The giant can hold the pole.','Gail can tie the rope.'],B:['The giant holds a long wooden pole.','Gail and a friend prepare the rope.','Each helper has a job.'],C:['The giant can hold the heavy pole steady.','Gail and her friend can reach the smaller parts and tie them.','They choose jobs that suit what each person can do.']},
{A:['They join two umbrellas.','They tie a knot.'],B:['Gail joins two umbrella handles with rope.','Her friend helps her tie a firm knot.','The giant holds the pole still.'],C:['Under the roof, Gail and her friend tie two handles together.','They pull gently to check that the knot holds.','The giant keeps the pole steady while they work.']},
{A:['They lift the umbrellas.','There is a gap.'],B:['They lift their first little roof.','A gap remains between the umbrellas.','“Rain could come through,” says Gail.'],C:['The helpers lift the joined umbrellas to inspect their work.','Gail notices a gap where the edges do not meet.','If they leave it open, rain will drip through.']},
{A:['They close the gap.','One edge goes over another.'],B:['They move the umbrellas closer.','One edge overlaps the next.','Now the gap is gone.'],C:['Instead of leaving the edges side by side, they overlap them.','Gail checks the middle while her friend checks the sides.','Their cover now has no open gap between the umbrellas.']},
{A:['The wind blows.','They lower the pole.'],B:['A gust of wind shakes their new roof.','“Lower it slowly!” calls Gail.','They bring the pole down together.'],C:['A gust catches the joined umbrellas as they lift them.','Gail asks everyone to lower the pole slowly together.','They return beneath the roof to make the frame stronger.']},
{A:['They make a strong frame.','The giant helps.'],B:['They add a crosspiece to the pole.','The giant holds it while the others tie it.','The frame becomes strong.'],C:['They add a wooden crosspiece to support the wide canopy.','The giant holds it firmly while the helpers secure the rope.','A stronger frame will spread the weight of the umbrellas.']},
{A:['They pull the rope.','They check each knot.'],B:['Gail checks one knot, then the next.','Her friend pulls the rope gently.','Nothing slips this time.'],C:['Before lifting again, they check every knot and connection.','Gail holds one end while her friend gives a gentle pull.','The rope stays firm, and the frame no longer wobbles.']},
{A:['“One, two, three!”','They lift together.'],B:['Everyone gets ready to lift.','“One, two, three!” counts Gail.','They raise the rainbow umbrella together.'],C:['The helpers wait until everyone is ready.','On Gail’s count, they lift at the same time.','The joined umbrellas rise smoothly above the giant’s head.']},
{A:['The giant is dry!','He smiles under the umbrella.'],B:['The rainbow umbrella covers both shoulders.','The giant looks up and smiles.','For the first time today, he is dry.'],C:['The giant steps beneath the wide rainbow canopy.','This time it covers his shoulders as well as his head.','He smiles as the rain rolls safely off the edges.']},
{A:['“Come under here!”','There is room to share.'],B:['The giant sees a friend in the rain.','“Come under here!” he calls.','Their umbrella has room to share.'],C:['A late helper arrives with wet sleeves.','The giant invites her beneath the wide canopy.','What began as help for one person now shelters several friends.']},
{A:['They walk slowly.','They stay together.'],B:['They walk slowly across the village green.','The giant carries the frame on his shoulders.','His friends stay close beneath the cover.'],C:['The giant rests the wooden beam across his shoulders, behind his head.','He takes small, slow steps so everyone can keep up.','They watch the path and stay together beneath their roof.']},
{A:['The sun comes out.','They feel proud.'],B:['The rain stops, and the sun comes out.','They set the umbrella down safely.','Everyone feels proud of their work.'],C:['When the rain ends, sunlight brightens the village.','They help set the umbrella down and admire their work.','Each helper feels proud of the part they played.']},
{A:['Small things can make something big.','Together, we can help!'],B:['“My little umbrella could not do it alone,” says Gail.','“But together, we made something big!”','The giant thanks every helper.'],C:['The giant thanks everyone, from the rope holders to the umbrella sharers.','No single helper could have built the wide cover alone.','By listening and working together, they made room for everyone.']}
];
