import type {LayeredBook} from './layered-three';
type Card=[string,string,string?];
// Concept cues distinguish words that share a character asset.
const cards:Record<LayeredBook,Record<string,Card>>={
 witch:{witch:['mira-standing.png',''],spell:['broomstick.png','✦ → ↑'],broomstick:['broomstick.png',''],hover:['mira-riding.png','↑  ━  ↓','above the ground'],wobble:['mira-riding.png','↶ ↷'],whisper:['mira-standing.png','🤫','a quiet voice'],sparkle:['star.svg','✧ ✦ ✧'],swirl:['portal.svg','↻'],chant:['mira-standing.png','♫  ♫  ♫','say it again'],copy:['card-grip.svg','▱ → ▱','watch · do'],attempt:['card-hover.svg','1 → 2','try again'],progress:['card-hover.svg','▁ ▃ ▅','a little more'],skill:['card-turn.svg',''],lesson:['teacher.png','1 · 2 · 3'],unsure:['mira-seated.png','?','Can I?'],capable:['mira-standing.png','✓','I can do this.'],almost:['hoop.svg','▰▰▰▱','not quite there'],yet:['mira-standing.png','… → ✓','not yet'],landing:['cushion.png','↓','come down safely'],succeed:['mira-standing.png','✓ ★','I did it!']},
 mirror:{mirror:['mirror.png',''],reflection:['mirror.png','👧 │ 👧'],portrait:['../shared-gail-v1/standing.png','▣','a picture of someone'],medal:['medal-gold.svg',''],puzzle:['tile-5.svg','▦'],dance:['swan.png','↶ ♫ ↷'],paint:['','🖌️ → 🎨'],compare:['','● ● │ ●●●','look at both'],similar:['','◒ ◓','almost the same'],different:['','● ▲','not the same'],equal:['','●● = ●●'],unique:['','● ● ★ ●','one of a kind'],strength:['rabbit-running.png','→ →','something you do well'],talent:['swan.png','♫ ★'],pace:['rabbit-running.png','→   →','your own speed'],admire:['swan.png','👏','Well done!'],value:['','♡','this matters to me'],own:['../shared-gail-v1/standing.png','↓','my own way'],improve:['','▁ → ▃ → ▅','better than before'],herself:['../shared-gail-v1/standing.png','↶','Gail herself']},
 'star-library':{library:['library.png',''],librarian:['librarian.png',''],shelf:['library.png','→ ▤','where books stand'],cover:['book.png','▣','the outside of a book'],page:['book.png','↓','one side of a sheet'],title:['book.png','The Fox and the Bridge','the name of the book'],chapter:['','1 │ 2 │ 3','parts of a book'],character:['card-beginning.png','↓','the fox'],setting:['card-middle.png','↔','by a stream'],event:['card-middle.png','→','the fox crosses'],clue:['card-middle.png','↓','the bridge'],predict:['card-beginning.png','? →','What might happen?'],retell:['card-ending.png','1 → 2 → 3','tell it again'],meaning:['book.png','💡','what it tells us'],summary:['book.png','▤ → ▱','the main things'],reason:['card-middle.png','because','The bridge is safe.'],evidence:['card-middle.png','🔎','a detail in the picture'],understand:['book.png','💡 ✓','Now I see why.'],remember:['book.png','↶ 💭','bring it to mind'],explain:['librarian.png','💬','tell how or why']}
};
export function layeredCard(book:LayeredBook,word:string):HTMLElement{
 const [file,cue,caption]=cards[book][word];const frame=document.createElement('div');frame.className='layered-word-visual';
 if(file){const image=document.createElement('img');image.src=`images/story/${book}-v1/${file}`;image.alt='';frame.append(image);}
 if(cue){const mark=document.createElement('span');mark.className='concept-cue';mark.textContent=cue;frame.append(mark);}
 if(caption){const label=document.createElement('small');label.textContent=caption;frame.append(label);}
 return frame;
}
