import {AdditiveBlending,BufferAttribute,BufferGeometry,Mesh,MeshBasicMaterial,OrthographicCamera,PlaneGeometry,Points,PointsMaterial,RepeatWrapping,Scene,SRGBColorSpace,TextureLoader,WebGLRenderer,type Material} from 'three';

export function mountMoonlight3D(host:HTMLElement,url:string,cell:number){
 const renderer=new WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.className='moonlight-webgl';renderer.domElement.setAttribute('aria-hidden','true');host.prepend(renderer.domElement);
 const scene=new Scene();const camera=new OrthographicCamera(-1,1,1,-1,.1,10);camera.position.z=2;
 const geometry=new PlaneGeometry(2,2);const loader=new TextureLoader();let base:Mesh|undefined,halo:Mesh|undefined;
 loader.load(url,texture=>{texture.colorSpace=SRGBColorSpace;texture.wrapS=texture.wrapT=RepeatWrapping;texture.repeat.set(.5,.5);texture.offset.set(cell%2*.5,cell<2?.5:0);const material=new MeshBasicMaterial({map:texture});base=new Mesh(geometry,material);scene.add(base);const glowMaterial=material.clone();glowMaterial.transparent=true;glowMaterial.opacity=.07;glowMaterial.blending=AdditiveBlending;halo=new Mesh(geometry,glowMaterial);halo.position.z=.04;halo.scale.set(1.025,1.025,1);scene.add(halo);});
 const count=38,positions=new Float32Array(count*3);for(let i=0;i<count;i++){positions[i*3]=Math.random()*2-1;positions[i*3+1]=Math.random()*2-1;positions[i*3+2]=.08+Math.random()*.25;}const dots=new BufferGeometry();dots.setAttribute('position',new BufferAttribute(positions,3));const particles=new Points(dots,new PointsMaterial({color:0xffe7a0,size:.016,transparent:true,opacity:.48,blending:AdditiveBlending}));scene.add(particles);
 const resize=()=>{const r=host.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);const aspect=r.width/r.height;camera.left=-aspect;camera.right=aspect;camera.top=1;camera.bottom=-1;camera.updateProjectionMatrix();if(base&&halo){base.scale.x=aspect;halo.scale.x=aspect*1.025;halo.scale.y=1.025;}};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 const start=performance.now();let frame=0;const animate=(now:number)=>{const t=(now-start)/1000;camera.zoom=1.035-Math.min(1,t/1.4)*.035;camera.position.x=Math.sin(t*.22)*.012;camera.position.y=Math.cos(t*.18)*.008;camera.updateProjectionMatrix();particles.rotation.z=t*.008;const pos=dots.getAttribute('position') as BufferAttribute;for(let i=0;i<count;i++){let y=pos.getY(i)+.00045*(i%3+1);if(y>1)y=-1;pos.setY(i,y);}pos.needsUpdate=true;renderer.render(scene,camera);frame=requestAnimationFrame(animate);};frame=requestAnimationFrame(animate);
 return ()=>{cancelAnimationFrame(frame);ro.disconnect();renderer.dispose();geometry.dispose();dots.dispose();(particles.material as Material).dispose();scene.traverse(o=>{if(o instanceof Mesh)(o.material as Material).dispose();});renderer.domElement.remove();};
}
