import type {ReadingLevel} from './dragon-text';
export const pirateText:Record<ReadingLevel,string[]>[]=[
 {A:['Gail sees a boat.','It is gold.'],B:['A gold paper boat shines by the bed.','Gail reaches for it.'],C:['Beside her bed, Gail finds a tiny boat folded from gold paper.','Its soft light makes her curious, and she reaches out to take a closer look.']},
 {A:['Gold smoke rises.','Gail goes in.'],B:['Gold smoke rises from the boat.','It opens a path to the sea.','Gail steps into the light.'],C:['Golden smoke curls out of the little paper boat and drifts across the room.','Through the glowing mist, Gail can see a sunny harbor.','Still in her star pajamas, she steps into the light.']},
 {A:['Here is a dock.','A seagull calls.'],B:['Gail stands on a wooden dock.','A seagull calls from a post.','The sea is bright and blue.'],C:['Gail arrives on a wooden dock above the bright blue water.','A seagull calls from a nearby post, as if it is welcoming her.','Small waves lap against the wood below her feet.']},
 {A:['Here is a pirate.','He has a chest.'],B:['A little pirate opens his chest.','There is a rope and a telescope.','An oar rests beside it.'],C:['A young pirate opens a wooden chest with a proud smile.','Inside are a coil of rope and a brass telescope, with an oar beside the lid.','He has everything he needs for a little adventure—or so he thinks.']},
 {A:['“Mine!” says the pirate.','He holds it all.'],B:['“Mine!” says the pirate.','He holds all the tools.','He will not share them.'],C:['“Mine! All mine!” says the pirate, gathering the tools into his arms.','He worries that sharing means he will never get them back.','So he keeps the rope, the oar, and the telescope close.']},
 {A:['Two friends come.','“Can we help?”'],B:['Two friends come to the dock.','They want to help.','The pirate shakes his head.'],C:['Two friends arrive with an idea: they could sail to the shining bay together.','They offer to help carry the tools, but the pirate shakes his head.','“I can do it myself,” he says.']},
 {A:['The oar slips.','The rope drops.'],B:['The pirate holds too much.','The oar slips and the rope drops.','He needs help.'],C:['The pirate tries to lift the oar while keeping the telescope under one arm.','The rope slips to the dock, and he nearly loses his grip.','Gail waits nearby, ready to help him put things down.']},
 {A:['The boat must wait.','One person cannot do it all.'],B:['The boat is still tied to the dock.','The pirate cannot do every job.','“What can we do?” asks Gail.'],C:['Their boat stays tied safely to the dock while the pirate looks at all the jobs.','He cannot row, watch the way, and handle the sail at the same time.','“Could we find a way for everyone to help?” Gail asks.']},
 {A:['“We can share.”','“We can take a turn.”'],B:['“We can share the tools,” says Gail.','“You can have a turn too.”','The pirate thinks about it.'],C:['“Sharing does not mean giving your things away forever,” Gail explains.','“We can use them carefully and take turns.”','The pirate looks at his friends and decides to try.']},
 {A:['He shares the oar.','His friend smiles.'],B:['The pirate gives the oar to his friend.','She holds it with both hands.','“I can row,” she says.'],C:['The pirate passes the wooden oar to the girl in the sailor shirt.','She holds it carefully with both hands and thanks him.','His arms already feel a little lighter.']},
 {A:['He shares the rope.','“I can help!”'],B:['The other friend takes the rope.','“I can help with the sail.”','The pirate smiles at him.'],C:['Next, the pirate lets his other friend hold the rope for the sail.','The boy checks that the loose end is clear.','Now each friend has a useful job, and the tools are no longer in a heap.']},
 {A:['Gail gives him the telescope.','“You can look.”'],B:['Gail gives the pirate his telescope.','“You can look for the bay.”','“Then it is my turn!”'],C:['Gail places the telescope in the pirate’s hands.','“You can watch for the bay first,” she says.','“When you are done, may I have a turn?” The pirate nods.']},
 {A:['Life jackets on!','Now they are ready.'],B:['They all put on life jackets.','They sit down in the boat.','Now they are ready to go.'],C:['Before leaving the dock, everyone puts on a life jacket and checks the straps.','They settle into the boat, keeping their weight low and their feet inside.','Only when everyone is ready do they set off.']},
 {A:['The oar moves.','Waves splash.'],B:['Their friend pulls the oar.','Little waves splash by the boat.','They move away from the dock.'],C:['The girl pulls the oar through the water in a slow, steady stroke.','Little waves curl away from the wooden hull.','With everyone helping, the boat finally moves toward the bay.']},
 {A:['Wind fills the sail.','The boat moves.'],B:['The boy holds the rope.','The wind fills the sail.','The boat glides over the waves.'],C:['A gentle breeze fills the cream sail, and the boy holds its rope steady.','The cloth sways above them while the boat glides across the water.','The pirate watches his friends work and begins to understand.']},
 {A:['“Look! The bay!”','Gail points.'],B:['The pirate looks through the telescope.','“I see the bay!” he says.','Gail points to the shining shore.'],C:['Through the telescope, the pirate spots a sheltered bay beyond the headland.','“There it is!” he calls, showing Gail the way.','She points toward the blue sparkles along the shore.']},
 {A:['“Your turn, Gail.”','He shares the telescope.'],B:['“Your turn,” says the pirate.','He gives Gail the telescope.','She looks, then gives it back.'],C:['Without being reminded, the pirate offers Gail the telescope.','She looks at the shining water, thanks him, and returns it when she is done.','His favorite tool is still his, and now they both have a happy memory.']},
 {A:['They reach the beach.','They help each other.'],B:['They reach the quiet beach.','They take off their life jackets on land.','Everyone helps carry the picnic.'],C:['At the sheltered beach, they step onto dry sand and take off their life jackets.','The tools are set down carefully, and everyone helps unload the picnic.','No one has to carry everything alone.']},
 {A:['They eat together.','“Some for you!”'],B:['The chest holds their picnic.','The pirate shares an apple with Gail.','They are happy together.'],C:['Their treasure chest now holds bread, fruit, and shells from the beach.','The pirate offers Gail an apple before taking one for himself.','The best part of this treasure is enjoying it together.']},
 {A:['Gail is home.','She will share too.'],B:['Gail is back in her room.','The little boat rests by her bed.','“A turn for you, a turn for me.”'],C:['Back in her room, Gail finds the little paper boat resting beside her bed.','She thinks about the pirate, who learned that sharing could bring his things back with a story.','“A turn for you, a turn for me,” she whispers with a smile.']}
];
