import type {ReadingLevel} from './dragon-text';
/** Same twenty events at three reading lengths; no extra plot at higher levels. */
export const princessVocabulary=['play','help','friend','together','princess','castle','gift','lonely','listen','share','smile','window','blocks','surprise','market','orange','basket','pinwheel','rain','laugh'] as const;
export const princessText:Record<ReadingLevel,string[]>[]=[
 {A:['Gail sees a castle.','She hears a sigh.'],B:['Gail walks to a quiet castle.','She hears a little sigh.','Who is inside?'],C:['Gail follows a path to a quiet castle.','A little sigh comes through an open window.','She stops to listen.']},
 {A:['Ella is a princess.','She sits by the window.'],B:['Princess Ella sits by the window.','She watches children play outside.','Gail comes into the room.'],C:['Princess Ella sits beside a tall window.','Outside, children are playing together.','Gail steps inside and wonders why Ella looks so quiet.']},
 {A:['Ella has a gift.','But she feels lonely.'],B:['Ella has many gifts.','She has blocks and toys.','But she feels lonely.'],C:['The room is full of gifts, blocks, and toys.','Yet Ella has no friend beside her.','A room full of things can still feel lonely.']},
 {A:['Gail wants to help Ella smile.','A surprise for Ella!'],B:['Gail wants to help Ella smile.','“I have a surprise!” she says.','She reaches for the blocks.'],C:['Gail wants to help, so she plans a surprise.','Perhaps a wonderful tower will make Ella smile.','She reaches for a box of blocks.']},
 {A:['Gail builds with blocks.','Ella wants to help.'],B:['Gail builds a tall tower.','“Can I help?” asks Ella.','“Wait! It is a surprise,” says Gail.'],C:['Gail carefully builds a tall tower with the blocks.','Ella reaches out and asks to help.','“Wait until it is finished!” says Gail, keeping her surprise a secret.']},
 {A:['The blocks fall.','Ella picks one up.'],B:['Oh no! The tower falls.','Gail looks down at the blocks.','Ella picks up a block to help.'],C:['The tall tower wobbles and falls across the rug.','Gail looks disappointed.','Ella picks up a block, hoping they can rebuild it together.']},
 {A:['Gail makes bubbles.','She tries a funny hat.'],B:['Gail tries more surprises.','She makes bubbles and plays music.','Then she puts on a funny hat.'],C:['Gail tries bubbles, music, and a funny paper hat.','She is so busy making surprises that she forgets to ask Ella.','The room becomes noisy.']},
 {A:['“Please stop,” says Ella.','Gail stops to listen.'],B:['Ella covers her ears.','“Please stop,” she says.','Gail stops and puts the hat down.'],C:['Ella covers her ears and quietly asks Gail to stop.','Gail puts down the paper hat.','At last, the room is quiet enough to listen.']},
 {A:['Gail sits with Ella.','She listens to her friend.'],B:['Gail sits beside Ella.','“What would you like?” she asks.','This time, she listens.'],C:['Gail sits down at Ella’s side instead of making another surprise.','“What would you like to do?” she asks.','Then she waits and listens to her friend.']},
 {A:['“Play with me,” says Ella.','“Let us play together!”'],B:['“I want a friend,” says Ella.','“Will you play with me?”','“Yes! Let us play together,” says Gail.'],C:['Ella points to the children beyond the window.','“I do not need another gift. I want a friend to play with.”','Gail smiles. “Let us choose something together.”']},
 {A:['They take a basket.','They walk to the market.'],B:['They ask Ella’s caregiver to come.','They take a basket to the market.','The three walk out together.'],C:['With her caregiver’s permission, Ella chooses a trip to the market.','Gail brings a basket, and the caregiver comes with them.','Together, they walk out through the castle gate.']},
 {A:['An orange rolls away.','Ella runs to help.'],B:['An orange rolls from a market stall.','Ella runs after it.','Gail follows her to help.'],C:['At the market, an orange rolls away from a fruit stall.','Ella spots it and runs a few steps to help.','Gail follows while their caregiver waits nearby.']},
 {A:['They pick up oranges.','The oranges go in the basket.'],B:['They pick up the oranges together.','Gail holds the basket for Ella.','“Thank you!” says the seller.'],C:['Ella picks up the oranges while Gail holds the basket.','They return the fruit to the grateful seller.','Working together feels better than watching a surprise.']},
 {A:['Gail has a pinwheel.','They share it.'],B:['Gail shows Ella a paper pinwheel.','They take turns in the open square.','It is fun to share.'],C:['In the open square, Gail takes out a paper pinwheel.','She and Ella take turns running while their caregiver watches.','The little paper wings spin as the friends share.']},
 {A:['Here comes the rain.','The pinwheel is wet.'],B:['Drops of rain begin to fall.','They hurry under an awning.','The wet pinwheel stops turning.'],C:['Suddenly, rain patters across the square.','The friends and their caregiver hurry under an awning.','Their soggy paper pinwheel will no longer turn.']},
 {A:['“I can help,” says Ella.','They fix the pinwheel.'],B:['“Let us fix it,” says Ella.','Gail holds the paper for her.','They make the pinwheel turn again.'],C:['Ella has an idea for repairing the pinwheel.','Gail holds the paper while Ella folds it carefully.','They straighten the wings together until it turns again.']},
 {A:['Ella makes a paper hat.','It slips over Gail’s nose!'],B:['Ella makes Gail a funny paper hat.','The hat is a little too big.','It slips down over Gail’s nose.'],C:['With a spare piece of paper, Ella folds a funny hat for Gail.','Gail puts it on, but one corner slips down.','It tickles the tip of her nose.']},
 {A:['“Achoo!” says Gail.','The friends laugh together.'],B:['“Achoo!” Gail gives a tiny sneeze.','Ella begins to laugh.','Soon both friends are laughing.'],C:['Gail gives a tiny sneeze, and the crooked hat bounces.','Ella begins to laugh, and Gail laughs too.','Nobody planned this smile; it grew from their shared fun.']},
 {A:['The friends play with blocks.','They build together.'],B:['Back at the castle, more friends join them.','They share the blocks.','This time, everyone helps to build.'],C:['Back at the castle, two children join Gail and Ella on the rug.','They share the blocks and build a little castle together.','Ella adds a piece of her own this time.']},
 {A:['Ella saves a place for Gail.','“Come and play, my friend!”'],B:['Ella pulls out a chair for Gail.','“Will you come and play tomorrow?”','Side by side, we laugh and play. A little friendship lights the day.'],C:['Ella pulls out a chair and saves a place beside her.','“Will you come back tomorrow?” she asks her new friend.','Side by side, we laugh and play. A little friendship lights the day.']}
];
