const gloss=`above=在上方|afraid=害怕的|apple=蘋果|apron=圍裙|away=離開|bag=袋子|basket=籃子|beach=海灘|bed=床|believe=相信|bell=鈴；門鈴|bird=鳥|birthday=生日|blanket=毯子|blocks=積木|boat=船|book=書|bowl=碗|brave=勇敢的|bread=麵包|bridge=橋|broom=掃帚|brush=畫筆|burn=燒焦|butter=奶油|butterfly=蝴蝶|cake=蛋糕|calendar=日曆|candle=蠟燭|cap=帽子|care=照顧；用心|castle=城堡|cat=貓|cave=洞穴|chest=寶箱|climb=爬|cloth=布|coat=外套|count=數數|cream=鮮奶油|cup=杯子|dock=碼頭|door=門|dragon=龍|draw=畫畫|drop=一滴；掉落|dry=乾的|duck=鴨子|ears=耳朵|eggs=雞蛋|eyes=眼睛|fall=跌倒；掉落|finish=完成|firefly=螢火蟲|first=首先|flour=麵粉|flower=花|fly=飛|forest=森林|fox=狐狸|friend=朋友|gail=瑜瑜|gap=縫隙|garden=花園|giant=巨人|gift=禮物|glasses=眼鏡|glide=滑翔|grandma=奶奶|grass=草地|hear=聽見|help=幫忙|high=高的|hill=山丘|hold=握住；扶住|home=家|hood=連帽斗篷|idea=主意|join=連接；加入|jump=跳|knot=繩結|ladder=梯子|lamp=燈|later=等一下；稍後|laugh=笑|leaf=葉子|left=左邊|lifejacket=救生衣|lift=舉起|lily=睡蓮|line=線條|list=清單|listen=聆聽|little=小的|lonely=孤單的|look=看|love=愛|mail=信件|manager=管理員|map=地圖|market=市場|mess=凌亂|milk=牛奶|mine=我的|mistake=錯誤|moon=月亮|mushroom=蘑菇|nest=鳥巢|next=接著|now=現在|number=數字|oar=船槳|open=打開|orange=柳橙|out=出去|oven=烤箱|over=越過；在上方|pan=烤模|paper=紙|path=小路|phone=電話|pinwheel=紙風車|pirate=海盜|plate=盤子|play=玩|pole=桿子|potion=藥水|practice=練習|princess=公主|proud=自豪的|quiet=安靜的|rack=冷卻架|rain=雨|right=右邊|river=河流|rock=石頭|roof=屋頂|room=房間|rope=繩子|sad=難過的|safe=安全的|sail=船帆；航行|seagull=海鷗|seven=七|share=分享|sink=水槽|sky=天空|sleep=睡覺|slice=一片|smile=微笑|smoke=煙|spatula=刮刀|spill=灑出|spoon=湯匙|stall=攤位|star=星星|start=開始|stem=莖|step=一步；步驟|stir=攪拌|stop=停止|strawberries=草莓|strong=強壯；牢固的|sugar=糖|surprise=驚喜|table=桌子|tail=尾巴|teeth=牙齒|telescope=望遠鏡|timer=計時器|tiny=很小的|together=一起|tree=樹|try=嘗試|turn=輪流；轉動|umbrella=雨傘|under=在下方|up=向上|valley=山谷|wait=等待|walk=走路|water=水；澆水|wave=揮手；波浪|wet=濕的|whisk=打蛋器|white=白色|wind=風|windmill=風車|window=窗戶|wing=翅膀|wizard=魔法師|wolf=狼|yellow=黃色`;
export const vocabularyGlossary:Record<string,string>=Object.fromEntries(gloss.split('|').map(row=>row.split('=')));
const groups:Record<string,string>={
 'above high over up':'⬆️','under':'⬇️','left':'⬅️','right next':'➡️','away out':'🚶','afraid':'😟','believe brave try practice':'💪','birthday cake slice':'🎂','care love':'❤️','count number seven':'🔢','finish':'✅','first step start now':'▶️','friend share together join':'🤝','gap':'↔️','glide fly wing':'🪽','hear listen ears':'👂','help hold lift':'🙌','idea':'💡','jump climb':'🧗','later wait timer':'⏳','laugh smile':'😄','line draw brush':'🖌️','list':'📋','little tiny':'🤏','lonely sad':'😔','look eyes':'👀','mess mistake':'😵','mine':'🙋','open door':'🚪','play turn':'🎲','proud':'😊','quiet':'🤫','safe':'🛟','sleep bed':'🛏️','strong':'💪','surprise':'🎁','walk':'🚶','white':'⚪','yellow':'🟡','wind':'💨','rain wet water drop spill':'💧','dry':'☀️','burn':'🔥','stir whisk spoon spatula':'🥄','flour sugar':'🥣','milk':'🥛','butter cream':'🧈','eggs':'🥚','bread':'🍞','bowl cup plate':'🍽️','oven pan rack':'🥘','apron coat hood cloth':'👕','phone':'📱','map path':'🗺️','forest tree grass garden leaf stem':'🌿','castle':'🏰','cave rock hill valley':'⛰️','river':'🏞️','sky moon star':'🌙','market stall':'🏪','home room roof':'🏠','lamp':'💡','table':'🪑','window':'🪟','book paper':'📖','calendar':'📅','mail':'✉️','manager':'🧑‍🔧','gail princess grandma':'👧','dragon':'🐉','cat':'🐈','wolf':'🐺','fox':'🦊','giant':'🧍','wizard':'🧙','pirate':'🏴‍☠️','bird seagull wing':'🐦','duck':'🦆','nest':'🪺','firefly':'✨','flower lily':'🌸','apple strawberries orange':'🍎','mushroom':'🍄','butterfly':'🦋','bag basket':'🧺','blanket':'🛌','blocks':'🧱','boat dock sail oar beach':'⛵','bridge':'🌉','broom':'🧹','bell':'🔔','candle':'🕯️','cap':'🧢','chest gift':'🎁','glasses':'👓','knot rope':'🪢','ladder':'🪜','lifejacket':'🛟','pinwheel windmill':'🌀','pole':'🪵','potion':'🧪','sink':'🚰','smoke':'💨','tail':'🐾','teeth':'🦷','telescope':'🔭','wave':'🌊'};
export const vocabularySymbols:Record<string,string>={};for(const[words,symbol]of Object.entries(groups))for(const word of words.split(' '))vocabularySymbols[word]=symbol;

vocabularySymbols.turn='🔄';

Object.assign(vocabularyGlossary,{bear:"熊",tile:"磁磚",clay:"黏土",shelf:"架子",reach:"伸手",bump:"碰撞",crack:"裂開",broken:"破碎的",piece:"碎片；一片",hide:"藏起來",worried:"擔心的",truth:"事實；真相",tell:"告訴",sorry:"抱歉",honest:"誠實的",adult:"大人",gloves:"手套",sweep:"清掃",repair:"修補",mosaic:"馬賽克拼貼"});

Object.assign(vocabularyGlossary,{lid:'蓋子',chime:'清脆的鈴聲',mist:'霧',float:'飄浮',breeze:'微風',scatter:'散開',spin:'旋轉',thunder:'雷聲',rumble:'隆隆聲',loud:'大聲的',angry:'生氣的',upset:'難受的',name:'說出名稱；說出感受',pause:'暫停',breathe:'呼吸',slow:'慢的',calm:'平靜的',gentle:'柔和的',need:'需要',again:'再一次'});
