import type {ReadingLevel} from './dragon-text';
export const wizardVocabulary=['wizard','later','now','potion','stir','burn','broom','stop','garden','water','flower','mess','list','step','first','next','start','finish','help','proud'] as const;
export const wizardText:Record<ReadingLevel,string[]>[]=[
{A:['Gail meets a wizard.','He waves from his door.'],B:['Gail visits a little stone house.','A wizard waves from the door.','“Come in!” he says.'],C:['Gail follows a winding path to a little stone house.','A friendly wizard opens the round door.','His tall hat tips as he welcomes her inside.']},
{A:['“I will do it later,” he says.','Gail sees a big mess.'],B:['Books and tools fill the room.','“I will tidy up later,” says the wizard.','He settles into his chair.'],C:['Books and tools lie all over the workshop floor.','“I will tidy up later,” says the wizard with a wave.','There always seems to be something more pleasant to do.']},
{A:['A potion bubbles.','It is time to stir.'],B:['A potion bubbles in a pot.','Gail points to the spoon.','“Is it time to stir?”'],C:['A potion bubbles inside the wizard’s little magic pot.','Gail notices the spoon waiting beside it.','“Does your potion need stirring?” she asks.']},
{A:['“Later,” says the wizard.','The potion starts to burn.'],B:['“I will stir it later,” says the wizard.','The potion turns brown.','A curl of smoke rises.'],C:['The wizard puts off stirring while he looks at a picture book.','Soon the potion turns brown and smells burnt.','A curl of smoke rises from the pot.']},
{A:['“Stop!” says Gail.','The wizard turns off the heat.'],B:['“Please stop the heat!” calls Gail.','The wizard turns the heat off with his wand.','Gail stays back while the pot cools.'],C:['“Please turn off the heat!” Gail calls from a safe distance.','The wizard uses his wand to stop the heat.','They leave the hot pot alone until it has cooled.']},
{A:['A broom sweeps by itself.','The wizard says, “Later.”'],B:['The magic broom sweeps the floor.','It needs a stop spell.','“I will stop it later,” says the wizard.'],C:['Across the room, a magic broom keeps sweeping.','The wizard knows it needs a stop spell.','“In a moment,” he says, turning back to his book.']},
{A:['The broom goes too fast.','What a mess!'],B:['The broom races around the room.','Papers fly into the air.','Now the mess is even bigger!'],C:['The broom speeds up and chases papers in circles.','Instead of cleaning, it scatters them across the floor.','Gail steps aside as the broom whizzes past.']},
{A:['The wizard says, “Stop!”','The broom is still.'],B:['“Stop!” says the wizard with his wand.','The broom becomes still.','He puts it safely by the wall.'],C:['At last, the wizard points his wand and says the stop spell.','The broom settles gently onto the floor.','He puts it by the wall before anyone trips over it.']},
{A:['They go to the garden.','A flower needs water.'],B:['Gail looks into the garden.','The flowers hang their heads.','“They need water,” she says.'],C:['Gail and the wizard step outside into the garden.','The flowers droop in the dry soil.','The watering can is nearby, but nobody has used it.']},
{A:['“Later,” he says again.','“Can we help now?” asks Gail.'],B:['“I will water them later,” he says.','Gail kneels by a drooping flower.','“Can we help it now?”'],C:['The wizard starts to say that he will water the flowers later.','Gail points to a drooping flower beside her.','“Could we help this one now?” she asks gently.']},
{A:['“There is too much to do!”','Gail has a list.'],B:['The wizard looks at all the jobs.','“There is too much to do!” he sighs.','Gail finds paper for a little list.'],C:['The wizard thinks about the potion, the papers, and the flowers.','So many unfinished jobs make it hard to choose one.','Gail brings him a sheet of paper.']},
{A:['“One small step,” says Gail.','“First, fill the can.”'],B:['“We can take one small step,” says Gail.','They draw a can on their list.','“First, fill the watering can.”'],C:['“We do not have to do everything at once,” Gail explains.','They draw three simple pictures on their list.','The first small step is to fill the watering can.']},
{A:['They start now.','Water goes into the can.'],B:['The wizard picks up the can.','Gail helps him fill it with water.','They have made a start!'],C:['The wizard picks up the empty can instead of saying later.','Gail helps him fill it at the garden tap.','The job has begun, and the first step already feels manageable.']},
{A:['Next, they water one flower.','They finish one small job.'],B:['Next, they water one flower.','Then they water the others.','They finish and mark their list.'],C:['Next, they gently water one flower, then move to the next.','Soon the whole little flowerbed has enough water.','They mark the first job as finished on their list.']},
{A:['One book goes on the shelf.','Gail helps with the next.'],B:['They go back to the messy room.','The wizard puts one book on the shelf.','Gail helps with the next book.'],C:['Back inside, they choose just one corner of the messy room.','The wizard puts a book on the shelf, and Gail gathers the next.','One small action makes the following action easier.']},
{A:['The cool pot is clean.','The wizard will stir now.'],B:['The wizard cleans the cool pot.','He makes a new potion and stirs it.','This time, he stays beside it.'],C:['Once the pot is cool, the wizard cleans it and starts a fresh potion.','He stays by the pot, stirring and watching carefully.','Gail watches from a safe distance as it turns a lovely green.']},
{A:['The broom moves slowly.','The wizard stops it on time.'],B:['The wizard lets the broom sweep one corner.','Then he says the stop spell.','The floor is clean and calm.'],C:['The wizard gives the broom one small corner to sweep.','As soon as it finishes, he uses the stop spell.','This time, papers stay neatly on the shelf.']},
{A:['The garden looks bright.','The wizard feels proud.'],B:['Later that afternoon, the flowers look bright.','The workshop is tidy too.','The wizard feels proud of his work.'],C:['Later that afternoon, the watered flowers have lifted their heads.','The workshop is tidy, and the fresh potion is ready.','The wizard feels proud because he followed each small step.']},
{A:['He sees one more book.','“I will do it now!”'],B:['The wizard notices one book on the floor.','“I will put it away now,” he says.','Gail smiles as he starts by himself.'],C:['Just as Gail is leaving, the wizard spots one more book on the floor.','This time, nobody needs to remind him.','“I will put it away now,” he says, and begins straight away.']},
{A:['“Start with one small step.”','Gail waves goodbye.'],B:['“Start with one small step,” says the wizard.','Gail waves goodbye at the door.','A little start can go a long way.'],C:['At the door, the wizard thanks Gail for her help.','He has learned that starting matters more than waiting for a perfect moment.','One little step today can make tomorrow easier.']}
];
