import {divisionLesson,divisionHint,divisionPrompt} from './division-model.mjs';
import {DivisionView} from './three-view.js';
const $=id=>document.getElementById(id),phases=['quotient','product','remainder'],titles={quotient:'① 試商',product:'② 商乘除數',remainder:'③ 相減、落下一位'};
const gradeTwoEntry=new URLSearchParams(location.search).get('grade')==='2';
let lesson=divisionLesson(gradeTwoEntry?84:1206,6),index=lesson.steps.findIndex(s=>!s.leading),phase='quotient',mode='demo',showAnswer=false,feedback='',timer=null,view,lengthSetting=gradeTwoEntry?2:4,divisorLength=1,voiceOn=false,utterance=null;
try{view=new DivisionView($('visual'));}catch{$('visual').textContent='此裝置無法顯示立體積木，可使用左側直式繼續練習。';}
const current=()=>lesson.steps[index],done=()=>index>=lesson.steps.length;
function narration(){const question=`${lesson.dividend} 除以 ${lesson.divisor}。`;if(done()||showAnswer)return `${question}商是 ${lesson.quotient}，餘數是 ${lesson.remainder}。驗算，${lesson.divisor} 乘以 ${lesson.quotient}，加上 ${lesson.remainder}，等於 ${lesson.dividend}。`;return `${question}第 ${index+1} 位，${{quotient:'試商',product:'商乘除數',remainder:'相減求餘數'}[phase]}。${mode==='demo'?divisionHint(lesson,index,phase):divisionPrompt(lesson,index,phase)}`;}
function stopSpeech(){window.speechSynthesis?.cancel();utterance=null;}
function syncVoiceButton(){const button=$('voice-toggle');button.setAttribute('aria-pressed',String(voiceOn));button.setAttribute('aria-label',voiceOn?'關閉語音說明':'開啟語音說明');button.title=voiceOn?'關閉語音說明':'開啟後朗讀題目與操作步驟';button.textContent=voiceOn?'🔊':'🔇';}
function speak(message){if(!voiceOn||!message)return;if(!window.speechSynthesis||typeof SpeechSynthesisUtterance==='undefined'){voiceOn=false;syncVoiceButton();$('feedback').textContent='這個瀏覽器沒有語音，請看畫面上的題目與說明。';return;}stopSpeech();const item=new SpeechSynthesisUtterance(message);utterance=item;item.lang='zh-TW';item.rate=.88;const voices=window.speechSynthesis.getVoices();item.voice=voices.find(v=>/^zh[-_]TW$/i.test(v.lang))||voices.find(v=>/^zh/i.test(v.lang))||null;item.onerror=e=>{if(utterance===item&&!['canceled','interrupted'].includes(e.error)){voiceOn=false;syncVoiceButton();$('feedback').textContent='語音暫時無法播放，仍可閱讀畫面說明。';}};try{window.speechSynthesis.speak(item);}catch{voiceOn=false;syncVoiceButton();$('feedback').textContent='語音暫時無法播放，仍可閱讀畫面說明。';}}
function stop(){clearTimeout(timer);timer=null;}
function reset(){stop();index=lesson.steps.findIndex(s=>!s.leading);phase='quotient';showAnswer=false;feedback='';render();}
function advance(){if(done())return;const p=phases.indexOf(phase);if(p<2)phase=phases[p+1];else{index++;phase='quotient';if(done())feedback=`完成！${lesson.dividend} ÷ ${lesson.divisor} ＝ ${lesson.quotient}${lesson.remainder?`，餘 ${lesson.remainder}`:'，剛好整除'}。`;}render();speak(narration());}
function board(){const n=lesson.digits.length,seen=k=>showAnswer||k<index,show=k=>showAnswer||k===index;
  const quotient=lesson.steps.map((s,k)=>`<div class="quotient-cell ${k===index?'current':''} ${seen(k)||show(k)&&phase!=='quotient'?'revealed':''}">${s.leading?'':seen(k)||show(k)&&phase!=='quotient'?s.digit:show(k)?'？':''}</div>`).join('');
  const digitRow=(value,k,visible,label)=>{const characters=visible?String(value).split(''):[],start=k+1-characters.length;return `<div class="work-row" aria-label="${label}${visible?' '+value:'，待填'}">${Array.from({length:n},(_,i)=>`<span class="work-digit">${visible&&i>=start&&i<=k?characters[i-start]:''}</span>`).join('')}</div>`;};
  const rows=lesson.steps.map((s,k)=>{if(s.leading)return '';if(!seen(k)&&!show(k))return '';const prod=seen(k)||show(k)&&phase==='remainder',rem=seen(k);return `<div class="work-block ${k===index?'active':''}" style="--right-blank:${n-1-k}"><span class="work-label">取下</span>${digitRow(s.partial,k,true,'取下')}<span class="work-label">乘積</span><div class="product-line">${digitRow(s.product,k,prod,'乘積')}</div><span class="work-label">餘數</span>${digitRow(s.remainder,k,rem,'餘數')}</div>`;}).join('');
  return `<div class="division-inner" style="--count:${n}"><div class="quotient-row"><div class="divisor-space"></div>${quotient}</div><div class="dividend-row"><div class="divisor-label"><input class="direct-number divisor-edit" data-edit="divisor" type="text" inputmode="numeric" maxlength="2" value="${lesson.divisor}" aria-label="除數，點此輸入新數字，按 Enter 套用" title="點此修改除數，按 Enter 套用"></div><div class="bracket"><input class="direct-number dividend-edit" data-edit="dividend" type="text" inputmode="numeric" maxlength="4" value="${lesson.dividend}" aria-label="被除數，點此輸入新數字，按 Enter 套用" title="點此修改被除數，按 Enter 套用"></div></div><div class="division-work">${rows}</div></div>`;
}
function render(){const finished=done(),s=current(),currentPhase=finished?'finished':phase;
  document.querySelectorAll('[data-length]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.length)===lengthSetting)));document.querySelectorAll('[data-divisor-length]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.divisorLength)===divisorLength)));
  $('demo-mode').setAttribute('aria-pressed',String(mode==='demo'));$('practice-mode').setAttribute('aria-pressed',String(mode==='practice'));$('show-answer').setAttribute('aria-pressed',String(showAnswer));$('show-answer').textContent=showAnswer?'隱藏完整直式':'查看完整直式';
  $('equation').textContent=`${lesson.dividend} ÷ ${lesson.divisor}${finished||showAnswer?` ＝ ${lesson.quotient}${lesson.remainder?` 餘 ${lesson.remainder}`:''}`:' ＝ ？'}`;$('progress').textContent=finished?'全部完成':`第 ${index+1} / ${lesson.steps.length} 位 · ${titles[phase]}`;$('board').innerHTML=board();
  $('phase-title').textContent=finished?'完成與驗算':titles[phase];$('instruction').textContent=finished?`${lesson.divisor} × ${lesson.quotient} ＋ ${lesson.remainder} ＝ ${lesson.dividend}；最後餘數 ${lesson.remainder} 小於除數 ${lesson.divisor}。`:mode==='demo'?divisionHint(lesson,index,phase):divisionPrompt(lesson,index,phase);$('feedback').textContent=feedback;
  $('step-answer').hidden=mode!=='practice'||finished;$('answer-label').firstChild.textContent=finished?'已完成':{quotient:'這一位的商',product:'乘積',remainder:'相減後餘數'}[phase];$('step-input').value='';$('step-input').max=phase==='quotient'?9:999;$('next-demo').hidden=mode!=='demo'||finished;$('play-demo').hidden=mode!=='demo'||finished;$('play-demo').textContent=timer?'Ⅱ 暫停示範':'▶ 播放示範';$('recap').textContent=finished?`驗算：${lesson.divisor} × ${lesson.quotient} ＋ ${lesson.remainder} ＝ ${lesson.dividend}`:'';
  $('left-label').textContent=finished?'最後餘數 '+lesson.remainder:phase==='remainder'?`相減後 ${s.remainder}`:`目前取下 ${s.partial}`;$('right-label').textContent=finished?'':phase==='quotient'?'':`本步乘積 ${s.product}`;if(view)view.update(finished?lesson.steps.at(-1):s,currentPhase);
}
function setProblem(dividend,divisor){lesson=divisionLesson(dividend,divisor);lengthSetting=String(dividend).length;divisorLength=String(divisor).length;$('settings').open=false;reset();speak(narration());}
$('board').addEventListener('focusin',e=>{if(e.target.matches('[data-edit]'))e.target.select();});
function applyDirectEdit(input){if(!input.matches('[data-edit]'))return;const field=input.dataset.edit,value=input.value.trim(),previous=lesson[field];if(value===String(previous))return;try{if(!/^\d+$/.test(value))throw Error('請直接輸入數字，再按 Enter 套用。');setProblem(field==='dividend'?Number(value):lesson.dividend,field==='divisor'?Number(value):lesson.divisor);}catch(err){input.value=previous;feedback=err.message;$('feedback').textContent=feedback;speak(err.message);}}
$('board').addEventListener('keydown',e=>{if(e.target.matches('[data-edit]')&&e.key==='Enter'){e.preventDefault();applyDirectEdit(e.target);e.target.blur();}});
$('board').addEventListener('focusout',e=>applyDirectEdit(e.target));
$('board').addEventListener('change',e=>applyDirectEdit(e.target));
$('step-answer').addEventListener('submit',e=>{e.preventDefault();if(done())return;const value=Number($('step-input').value),expected=current()[phase==='quotient'?'digit':phase];if(value!==expected){feedback=phase==='quotient'?`這一位的商要在 0～9 之間，乘除數後不能超過 ${current().partial}。`:phase==='product'?`請用這一位的商乘 ${lesson.divisor}，再對齊目前的數位。`:`請用 ${current().partial} 減去本步乘積，餘數要小於 ${lesson.divisor}。`;$('feedback').textContent=feedback;speak(feedback);return;}feedback=phase==='remainder'?'這一步完成，接著看下一位。':'正確，繼續下一步。';advance();});
$('random').onclick=()=>{const min=10**(lengthSetting-1),max=10**lengthSetting-1,dMin=divisorLength===1?1:10;const dividend=min+Math.floor(Math.random()*(max-min+1)),dMax=Math.min(divisorLength===1?9:99,dividend),divisor=dMin+Math.floor(Math.random()*(dMax-dMin+1));setProblem(dividend,divisor);};
document.querySelectorAll('[data-length]').forEach(b=>b.onclick=()=>{lengthSetting=Number(b.dataset.length);render();speak(`被除數位數設為 ${lengthSetting} 位。按骰子產生新一題。`);});document.querySelectorAll('[data-divisor-length]').forEach(b=>b.onclick=()=>{divisorLength=Number(b.dataset.divisorLength);render();speak(`除數位數設為 ${divisorLength} 位。按骰子產生新一題。`);});
$('demo-mode').onclick=()=>{mode='demo';reset();speak(`示範模式。${narration()}`);};$('practice-mode').onclick=()=>{mode='practice';reset();speak(`操作模式。${narration()}`);};$('restart').onclick=()=>{reset();speak(`已從頭開始。${narration()}`);};$('show-answer').onclick=()=>{showAnswer=!showAnswer;render();speak(showAnswer?`完整直式。${narration()}`:`已隱藏完整直式。${narration()}`);};$('hint').onclick=()=>{$('feedback').textContent=done()?`用商乘除數再加餘數：${lesson.divisor} × ${lesson.quotient} ＋ ${lesson.remainder} ＝ ${lesson.dividend}。`:divisionHint(lesson,index,phase);speak($('feedback').textContent);};$('next-demo').onclick=()=>{stop();feedback='';advance();};
$('play-demo').onclick=()=>{if(timer){stop();stopSpeech();render();speak('已暫停示範。');return;}const tick=()=>{if(done()){stop();render();return;}advance();if(!done())timer=setTimeout(tick,voiceOn?Math.max(6000,Math.min(24000,narration().length*330)):1400);else timer=null;render();};timer=setTimeout(tick,voiceOn?3200:1400);render();speak('開始播放示範。');};
$('voice-toggle').onclick=()=>{if(!voiceOn&&(!window.speechSynthesis||typeof SpeechSynthesisUtterance==='undefined')){$('feedback').textContent='這個瀏覽器沒有語音，請看畫面上的題目與說明。';return;}voiceOn=!voiceOn;syncVoiceButton();if(voiceOn)speak(`語音說明已開啟。${narration()}`);else{if(timer){stop();render();}stopSpeech();}};
$('back').onclick=e=>{stop();stopSpeech();if(parent!==window){e.preventDefault();parent.postMessage({type:'math-teaching-close'},location.origin);}};document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();stopSpeech();render();}});window.addEventListener('pagehide',()=>{stop();stopSpeech();view?.destroy();});syncVoiceButton();render();
