import {fractionLesson,fractionSteps} from './fraction-model.mjs';
import {FractionView} from './three-view.js';
const root=document.querySelector('#math-teaching'),params=new URLSearchParams(location.search);let same=params.get('same')==='1',s=fractionLesson(1,4,1,4,params.get('op')==='sub'?'sub':'add'),step=0,mode='demo',timer=null,hint=false,solved=false,feedback='',view;
const btn=(id,label,disabled=false)=>`<button type="button" data-action="${id}" ${disabled?'disabled':''}>${label}</button>`;
function stop(){clearTimeout(timer);timer=null;}
try{view=new FractionView((side,n)=>{if(mode!=='practice'||step!==0)return;s=fractionLesson(side===0?n:s.a,s.d,side===1?n:s.b,s.e,s.op);solved=false;render();});}catch{feedback='此裝置使用平面切片，仍可完成教學。';}
function render(){const focus=document.activeElement?.dataset.action;const steps=fractionSteps(s),den=step===3?s.reducedDenominator:s.denominator,num=step===3?s.reducedNumerator:s.numerator;root.innerHTML=`<div class="mw"><header>${btn('exit','← 返回數學')}<div><small>LEARNING PLANET · FRACTIONS</small><h1>分數加減 · 立體切片</h1></div></header><form class="fraction-form"><label>左分子<input name="a" aria-label="左分子" type="number" min="0" max="${s.d}" value="${s.a}" required></label><label>左分母<input name="d" aria-label="左分母" type="number" min="1" max="10" value="${s.d}" required></label><select name="op" aria-label="加或減"><option value="add" ${s.op==='add'?'selected':''}>＋ 加法</option><option value="sub" ${s.op==='sub'?'selected':''}>− 減法</option></select><label>右分子<input name="b" aria-label="右分子" type="number" min="0" max="${s.e}" value="${s.b}" required></label><label>右分母<input name="e" aria-label="右分母" type="number" min="1" max="10" value="${s.e}" ${same?'readonly':''} required></label><button type="submit">套用分數</button>${btn('denmode',same?'切換異分母練習':'切換同分母練習')}<span>${same?'同分母課程：調整左分母時，右邊一起變更。':'兩邊分母皆可設為 1～10。'}分子為 0～分母。</span></form><div class="layout"><section class="desk"><div class="equation">${s.a}/${s.d} ${s.op==='add'?'＋':'−'} ${s.b}/${s.e}${step>=2?'＝'+num+'/'+den:''}</div><div class="fraction-labels">${step<2?`<span>左：${step?s.left:s.a}/${step?s.denominator:s.d}</span><span>右：${step?s.right:s.b}/${step?s.denominator:s.e}</span>`:`<span>${num<0?'負值，圖示為其大小；':''}結果：${num}/${den}${Math.abs(num)>den?'（'+Math.floor(Math.abs(num)/den)+' 個完整圓盤與剩餘切片）':''}</span>`}</div><div id="fraction-scene"></div><p class="fraction-note">${steps[step]}</p><div class="actions">${btn('prev','上一步',step===0)}${btn('next',step===0?'看通分切片':step===1?'計算加減':'約分切片',step===3)}</div></section><aside><div class="modes">${btn('demo','示範')}${btn('practice','操作')}${btn('review','回顧',!solved)}</div><h3>${['認識分數','通分','加減切片','約分'][step]}</h3>${mode==='review'?steps.map(t=>`<p>${t}</p>`).join(''):`<p>${mode==='practice'&&step===0?'可點圓盤的第幾片來設定分子；清空請輸入 0。再按下一步觀察。':'依序觀察相同大小的切片如何計算。'}</p>`}${hint?`<p class="hint">${steps[step]} 分母表示一個完整圓盤分成幾等份，不是兩個分母相加。</p>`:''}${mode==='practice'&&step===2&&!solved?'<form class="answer"><label>最簡分數分子<input name="n" aria-label="答案分子" type="number" required></label><label>分母<input name="d" aria-label="答案分母" type="number" min="1" required></label><button>確認答案</button></form>':''}<p role="status">${feedback}</p><div class="actions">${mode==='demo'?btn('play',timer?'暫停示範':'播放示範'):btn('hint','給我提示')}${btn('reset','重新觀察')}</div><p class="caption">分母 1～10 的異分母題，通分後可能多於 10 片（最多 90）。約分前後總量相同。負數先看差的大小。</p></aside></div></div>`;
const scene=root.querySelector('#fraction-scene');if(view){scene.append(view.element);view.update(s,step,mode==='practice'&&step===0);}else{const disk=(n,d)=>`<div class="fraction-flat">${Array.from({length:d},(_,i)=>`<span class="${i<n?'filled':''}">1/${d}</span>`).join('')}</div>`;scene.innerHTML=step<2?disk(step?s.left:s.a,step?s.denominator:s.d)+disk(step?s.right:s.b,step?s.denominator:s.e):Array.from({length:Math.max(1,Math.ceil(Math.abs(num)/den))},(_,i)=>disk(Math.min(den,Math.max(0,Math.abs(num)-i*den)),den)).join('');}if(focus)root.querySelector(`[data-action="${focus}"]`)?.focus({preventScroll:true});}
root.addEventListener('input',e=>{if(e.target.name==='d'&&e.target.closest('.fraction-form')){const form=e.target.form;form.elements.a.max=e.target.value;if(same){form.elements.e.value=e.target.value;form.elements.b.max=e.target.value;}}if(e.target.name==='e'&&e.target.closest('.fraction-form'))e.target.form.elements.b.max=e.target.value;});
root.addEventListener('focusin',e=>{if(e.target.closest('form'))stop();});
root.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);stop();if(e.target.classList.contains('fraction-form')){try{s=fractionLesson(Number(data.get('a')),Number(data.get('d')),Number(data.get('b')),Number(data.get(same?'d':'e')),String(data.get('op')));step=0;solved=false;feedback='';hint=false;}catch(err){feedback=err.message;}render();return;}solved=Number(data.get('n'))===s.reducedNumerator&&Number(data.get('d'))===s.reducedDenominator;feedback=solved?'答對了！可看約分切片與回顧。':'請檢查加減後的分子，並將分子、分母除以共同因數。';if(solved)step=3;render();});
root.addEventListener('click',e=>{const el=e.target.closest('button'),id=el?.dataset.action;if(!id||el.disabled)return;if(id==='exit'){stop();if(parent!==window)parent.postMessage({type:'math-teaching-close'},location.origin);else location.href='index.html';return;}if(id==='play'){if(timer){stop();render();return;}if(step===3)step=0;const tick=()=>{step++;if(step<3)timer=setTimeout(tick,3000);else timer=null;render();};timer=setTimeout(tick,3000);render();return;}stop();feedback='';hint=false;if(id==='denmode'){same=!same;if(same)s=fractionLesson(s.a,s.d,Math.min(s.b,s.d),s.d,s.op);step=0;solved=false;}if(id==='next')step=Math.min(3,step+1);if(id==='prev')step=Math.max(0,step-1);if(id==='hint')hint=true;if(id==='reset')step=0;if(id==='demo'||id==='practice'){mode=id;step=0;solved=false;}if(id==='review'&&solved){mode='review';step=3;}render();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();render();}});window.addEventListener('pagehide',()=>{stop();view?.destroy();});render();
