import {createMultiplication,placeOne,multiplicationHint,multiplicationRecap} from './multiplication-model.mjs';
import {MultiplicationView} from './three-view.js';
const root=document.querySelector('#math-teaching');let demo=createMultiplication(3,4),practice=createMultiplication(3,4),mode='demo',solved=false,timer=null,view,feedback='',hint=false,array=false,swapped=false;
const state=()=>mode==='demo'?demo:practice;
root.addEventListener('focusin',e=>{if(e.target.closest('.custom'))stop();});
const button=(id,label,disabled=false)=>`<button type="button" data-action="${id}" ${disabled?'disabled':''}>${label}</button>`;
try{view=new MultiplicationView(g=>place(g));}catch{feedback='此裝置改用平面教具，仍可完成全部操作。';}
function stop(){clearTimeout(timer);timer=null;}
function place(group){const s=state();if(view?.busy)return;const next=placeOne(s,group);if(next===s){feedback='請先放滿發亮的這一組，每組數量要相同。';render();return;}if(mode==='demo')demo=next;else practice=next;feedback='';hint=false;render();}
function play(){if(mode!=='demo')return;stop();if(demo.placed===demo.a*demo.b)demo=createMultiplication(demo.a,demo.b);const tick=()=>{if(document.hidden){stop();return;}place(Math.floor(demo.placed/demo.a));if(demo.placed<demo.a*demo.b){timer=setTimeout(tick,650);}else timer=null;render();};timer=setTimeout(tick,650);render();}
function render(){const s=state(),done=s.placed===s.a*s.b;root.innerHTML=`<div class="mw"><header>${button('exit','← 返回數學')}<div><small>LEARNING PLANET · MATH DESK</small><h1>乘法立體教學</h1></div></header><form class="custom"><label>每組 <input name="a" aria-label="每組數量" type="number" min="1" max="9" step="1" required value="${s.a}"> 個</label><label>共 <input name="b" aria-label="組數" type="number" min="1" max="9" step="1" required value="${s.b}"> 組</label><button type="submit">套用數字</button><span>1～9；套用後重新開始本題</span></form><div class="layout"><section class="desk"><div class="desk-top"><div class="equation">${s.a} × ${s.b} ＝ ${solved||mode==='demo'&&done?s.a*s.b:'？'}</div><span class="tag">${mode==='demo'?'看示範':mode==='practice'?'動手做':'回顧'}</span></div><div class="boards three-boards"></div><div class="mul-summary">每組 ${s.a} 個，共 ${s.b} 組。已放 ${s.placed} 個。<br>${Array(s.b).fill(s.a).join('＋')}${done?'＝'+s.a*s.b:''}</div><div class="actions">${button('array',array?'看分組托盤':'排成長方形',!done)}${button('swap',swapped?'看原來排列':'比較交換乘數',!done)}</div>${swapped?`<p>每組 ${s.b} 個，共 ${s.a} 組；總數不變。</p>`:''}</section><aside><div class="modes">${button('demo','示範')}${button('practice','操作')}${button('review','回顧',!solved)}</div><h3>${mode==='review'?'你做到了！':done?'算算總數':'一組一組放'}</h3>${mode==='review'?multiplicationRecap(s).map(t=>`<p>${t}</p>`).join(''):`<p>每組放 ${s.a} 個，依序完成 ${s.b} 組。</p>${hint?`<p class="hint">${multiplicationHint(s)}</p>`:''}`}${mode==='practice'&&done&&!solved?'<form class="answer"><label>總共有幾個？<input name="answer" aria-label="計算結果" type="number" min="1" max="81" required></label><button>確認答案</button></form>':''}<p class="mul-status" role="status">${feedback}</p><div class="actions">${mode==='demo'?button('play',timer?'暫停示範':'播放示範')+button('step','只看下一步',done):mode==='practice'?button('place','放入一顆積木',done)+button('hint','給我提示'):button('replay','重播示範')}${button('reset','這題重來')}</div><p class="caption">點亮色托盤或使用放入按鈕。每顆積木代表 1；不計時、不扣星幣。</p></aside></div></div>`;
const host=root.querySelector('.boards');if(view){host.replaceChildren(view.element);view.update(s,mode,array,swapped);}else{host.className='flat-groups';host.innerHTML=Array.from({length:s.b},(_,g)=>`<button data-group="${g}" ${mode!=='practice'||done?'disabled':''}>第 ${g+1} 組：${'🟨'.repeat(Math.max(0,Math.min(s.a,s.placed-g*s.a)))||'空'}</button>`).join('');}}
root.addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(form.classList.contains('custom')){const data=new FormData(form);try{const next=createMultiplication(Number(data.get('a')),Number(data.get('b')));stop();demo=next;practice=createMultiplication(next.a,next.b);mode='demo';solved=false;array=false;swapped=false;feedback='';hint=false;}catch(error){feedback=error.message;}render();return;}const s=practice;if(mode!=='practice'||s.placed!==s.a*s.b)return;solved=Number(new FormData(form).get('answer'))===s.a*s.b;feedback=solved?'答對了！可以打開回顧。':'再用連加算一次，每組的數量相同。';render();});
root.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.dataset.group!==undefined){place(Number(el.dataset.group));return;}const id=el.dataset.action;if(!id)return;
if(id==='exit'){stop();if(parent!==window)parent.postMessage({type:'math-teaching-close'},location.origin);else location.href='index.html';return;}
if(id==='play'){if(timer){stop();render();}else play();return;}stop();
if(id==='step'||id==='place'){place(Math.floor(state().placed/state().a));return;}
if(id==='hint')hint=true;
if(['demo','practice','review'].includes(id)){if(id==='review'&&!solved)return;mode=id;array=false;swapped=false;feedback='';}
if(id==='array'){array=!array;swapped=false;}
if(id==='swap'){array=true;swapped=!swapped;}
if(id==='reset'||id==='replay'){const s=state();if(id==='replay')mode='demo';if(mode==='demo')demo=createMultiplication(s.a,s.b);else{practice=createMultiplication(s.a,s.b);mode='practice';solved=false;}array=false;swapped=false;feedback='';hint=false;}
render();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();view?.finish();render();}});window.addEventListener('pagehide',()=>{stop();view?.destroy();});render();
