"""Refresh reader data from the authored text and single-source layer manifests."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
books={}
for name in ['witch','mirror','star-library']:
    data=json.loads((root/f'images/story/{name}-v1/assets.json').read_text())
    rows=[line.split('\t') for line in (root/f'docs/story-plans/reader-three/{name}.tsv').read_text().splitlines()]
    assert len(rows)==20 and all(len(row)==8 for row in rows)
    books[name]={'title':data['englishTitle'],'chineseTitle':data['title'],'backgrounds':data['backgrounds'],'layouts':data['pages'],'rows':rows}
(root/'src/story/interactive/layered-three-data.ts').write_text('// Generated by scripts/build-layered-three-data.py. Edit reader-three TSV or assets.json.\nexport const layeredThreeData = '+json.dumps(books,ensure_ascii=False)+';\nexport const layeredThreeQuiz = '+(root/'docs/story-plans/reader-three/questions.json').read_text()+';\n')

with (root/'src/story/interactive/layered-three-data.ts').open('a') as out:
    out.write('export const layeredThreeQuestionScenes = '+(root/'docs/story-plans/reader-three/question-scenes.json').read_text()+';\n')
