# Deploy to Firebase Hosting on merge to main
# https://firebase.google.com/docs/hosting/github-integration

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEARNPLANET_CCE52 }}
          channelId: live
          projectId: learnplanet-cce52
